[package]
name = "scatter-panning"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# Empty workspace needed so cargo doesn't try to add example as a workspace member
[workspace]

[dependencies]
avenger-vega = { path = "../../avenger-vega" }
avenger-wgpu = { path = "../../avenger-wgpu" }
avenger = { path = "../../avenger" }

cfg-if = "1"
winit = "0.28"
log = "0.4"
wgpu = "0.18"
pollster = "0.3"
serde_json = { version = "1.0.111" }
rand = "0.8.5"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "0.18", features = ["webgl"]}
wasm-bindgen = "=0.2.87"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3.53", features = [
    "Document",
    "Window",
    "Element",
]}