[package]
name = "avenger-chart-transforms"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-chart-cartesian = { path = "../avenger-chart-cartesian" }
avenger-chart-core = { path = "../avenger-chart-core" }
async-trait = { workspace = true }
chrono = { workspace = true }
datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-functions-aggregate = "48.0.1"
datafusion-proto = "48.0.1"
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.0"
tracing = { workspace = true }
typetag = "0.2"

[dev-dependencies]
arrow = { workspace = true }
bincode = "1.3"
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
