[package]
name = "avenger-chart-transforms"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-chart-cartesian = { path = "../avenger-chart-cartesian" }
avenger-chart-core = { path = "../avenger-chart-core" }
avenger-chart-lang-types = { path = "../avenger-chart-lang-types" }
avenger-chart-schema = { path = "../avenger-chart-schema" }
avenger-common = { path = "../avenger-common" }
async-trait = { workspace = true }
chrono = { workspace = true }
datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-functions-aggregate = "54.0.0"
datafusion-proto = { version = "54.0.0", default-features = false }
indexmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.0"
tracing = { workspace = true }
typetag = "0.2"

[dev-dependencies]
arrow = { workspace = true }
bincode = "1.3"
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
