[package]
name = "avenger-text"
version = "0.0.8"
edition = "2021"

[features]
serde = ["dep:serde"]
cosmic-text = ["dep:cosmic-text", "lazy_static"]
fontdb = ["dep:fontdb"]
typst-math = ["dep:avenger-typst"]
typst-math-raster = ["typst-math", "avenger-typst/raster"]
default = ["serde", "cosmic-text"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
image = { workspace = true }
unicode-segmentation = "1.12.0"
lyon_path = { workspace = true }
strum = { workspace = true }
ordered-float = { workspace = true }
svgtypes = { workspace = true }
ttf-parser = { workspace = true }

[dependencies.cosmic-text]
workspace = true
optional = true

[dependencies.fontdb]
workspace = true
optional = true

[dependencies.lazy_static]
workspace = true
optional = true

[dependencies.avenger-typst]
path = "../avenger-typst"
optional = true
default-features = false
features = ["vendor-typst"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.67", features = [
    "Document",
    "Window",
    "Element",
    "Performance",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "TextMetrics",
    "ImageData"
]}
