[package]
name = "avenger-text"
version = "0.0.8"
edition = "2021"

[features]
serde = ["dep:serde", "avenger-typst-label/serde"]
default = ["serde"]

[dependencies]
tracing = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
image = { workspace = true }
lyon_path = { workspace = true }
strum = { workspace = true }
ordered-float = { workspace = true }
brotli = { workspace = true }
avenger-color = { path = "../avenger-color" }
avenger-fonts = { path = "../avenger-fonts" }
avenger-format = { path = "../avenger-format" }

[dependencies.avenger-typst-label]
path = "../avenger-typst-label"
default-features = false
features = ["raster"]

[dev-dependencies]
chrono = { workspace = true }
avenger-format-datetime-d3 = { path = "../avenger-format-datetime-d3" }
avenger-format-number-d3 = { path = "../avenger-format-number-d3" }
chrono-tz = { workspace = true }
