#!/usr/bin/env python3
"""Generate supplemental number data from the pinned CLDR archive."""
import hashlib
import json
from pathlib import Path
import re
from tempfile import TemporaryDirectory
import urllib.request
import zipfile
import unicodedata

CLDR_VERSION = "48.2.1"
CLDR_SHA256 = "6435a529c9be2f9cbc57ba9d0e577c9c4aca90c109bb7156a4f057dfaf2a626f"
ROOT = Path(__file__).resolve().parents[2]


def rust(value):
    escaped = value.replace('\\', '\\\\').replace('"', '\\"')
    return '"' + ''.join('\\u{' + format(ord(c), 'x') + '}' if unicodedata.category(c) in ('Cf', 'Cc', 'Zl', 'Zp') else c for c in escaped) + '"'


def grouping_sizes(pattern):
    """Read primary and secondary grouping widths from the numeric blueprint."""
    parts = re.search(r'[#0][#0,]*', pattern)[0].split(',')
    primary = len(parts[-1]) if len(parts) > 1 else 0
    secondary = len(parts[-2]) if len(parts) > 2 else primary
    return primary, secondary


def tag(locale):
    """Spell identifiers as ICU4X data locales do, with lowercase variants."""
    language, *rest = locale.split('-')
    def subtag(s):
        if len(s) == 4 and s.isalpha():
            return s.title()
        if (len(s) == 2 and s.isalpha()) or (len(s) == 3 and s.isdigit()):
            return s.upper()
        return s.lower()
    return '-'.join([language.lower(), *map(subtag, rest)])


def ancestors(locale, parents, likely):
    """Follow CLDR inheritance, which the runtime walks with ICU4X's fallback chain."""
    while True:
        if locale in parents:
            locale = parents[locale]
        elif '-' not in locale:
            return
        else:
            language, script = locale.split('-')[:2]
            if locale.count('-') == 1 and len(script) == 4 and likely.get(language, '').split('-')[1:2] != [script]:
                return
            locale = locale.rsplit('-', 1)[0]
        if locale in ('root', 'und'):
            return
        yield locale


def symbol_rows(z, coverage):
    """Read symbols and overrides for every covered locale and numbering system."""
    rows = {}
    for name in sorted(z.namelist()):
        if not name.startswith('cldr-numbers-full/main/') or not name.endswith('/numbers.json'):
            continue
        locale = name.split('/')[-2]
        data = json.loads(z.read(name))['main'][locale]['numbers']
        parent = locale
        while parent not in coverage and '-' in parent:
            parent = parent.rsplit('-', 1)[0]
        # The root locale, `und`, has number data but no coverage level.
        if parent not in coverage and locale != 'und':
            continue
        for key, val in data.items():
            if not key.startswith('symbols-numberSystem-') or 'nan' not in val:
                continue
            nu = key.removeprefix('symbols-numberSystem-')
            def formats(kind):
                return data.get(f'{kind}Formats-numberSystem-{nu}', data[f'{kind}Formats-numberSystem-latn'])
            ordinary = (val['decimal'], val['group'], *grouping_sizes(formats('decimal')['standard']))
            monetary = (val.get('currencyDecimal', val['decimal']), val.get('currencyGroup', val['group']), *grouping_sizes(formats('currency')['standard']))
            accounting = grouping_sizes(formats('currency')['accounting'])
            percent = grouping_sizes(formats('percent')['standard'])
            monetary_value = 'Some(Monetary {{ decimal: {}, group: {}, primary: {}, secondary: {} }})'.format(*map(rust, monetary[:2]), *monetary[2:])
            rows[f'{tag(locale)}/{nu}'] = (
                ('nan', rust(val['nan'])),
                ('infinity', rust(val['infinity'])),
                ('exponent', rust(val['exponential'])),
                ('percent', rust(val['percentSign'])),
                ('permille', rust(val['perMille'])),
                ('monetary', monetary_value if monetary != ordinary else 'None'),
                ('percent_grouping', f'Some({percent})' if percent != ordinary[2:] else 'None'),
                ('accounting_grouping', f'Some({accounting})' if accounting != monetary[2:] else 'None'),
            )
    return rows


def generate(z):
    # The plural operand adapter maps exponents outside a byte to 6 while retaining the quantity.
    plurals = json.loads(z.read('cldr-core/supplemental/plurals.json'))['supplemental']['plurals-type-cardinal']
    exponent_clauses = {
        clause.strip() for rules in plurals.values() for rule in rules.values()
        for clause in re.split(r'\band\b|\bor\b', rule.split('@')[0])
        if re.search(r'\b[ec]\b', clause)
    }
    if exponent_clauses != {'e = 0', 'e != 0..5'}:
        raise ValueError('Review plural exponent normalization for the new CLDR rules')
    header = ['// Generated by tools/icu-number-reference/generate_data.py.',
              f'// CLDR {CLDR_VERSION}; archive SHA-256: {CLDR_SHA256}.',
              '// Unicode data license: data/LICENSE.']
    coverage = json.loads(z.read("cldr-core/coverageLevels.json"))["coverageLevels"]
    supplemental = json.loads(z.read('cldr-core/supplemental/parentLocales.json'))['supplemental']
    parents = {tag(k): tag(v) for k, v in supplemental['parentLocales']['parentLocale'].items()}
    likely = json.loads(z.read('cldr-core/supplemental/likelySubtags.json'))['supplemental']['likelySubtags']
    rows = symbol_rows(z, coverage)
    # A row equal to its nearest ancestor row is found by the runtime's fallback walk.
    kept = {}
    for key, row in rows.items():
        locale, nu = key.rsplit('/', 1)
        inherited = next((rows[f'{a}/{nu}'] for a in ancestors(locale, parents, likely) if f'{a}/{nu}' in rows), None)
        if inherited != row:
            kept[key] = row
    values = sorted(set(kept.values()), key=repr)
    indices = {v: i for i, v in enumerate(values)}
    out = header + ['static SYMBOL_VALUES: &[Symbols] = &[']
    out += ['    Symbols { ' + ', '.join(f'{field}: {value}' for field, value in row) + ' },' for row in values]
    out += ['];', 'static SYMBOLS: &[(&str, usize)] = &[']
    out += [f'    ({rust(key)}, {indices[row]}),' for key, row in sorted(kept.items())]
    out += ['];', '/// Locales with CLDR plural rules; others inherit by truncation, reaching root.',
            'static PLURAL_LOCALES: &[&str] = &[']
    names = sorted(tag(k) for k in plurals)
    out += ['    ' + ' '.join(f'{rust(k)},' for k in names[i:i + 10]) for i in range(0, len(names), 10)]
    out += ['];']
    # ICU4X files a locale's unit names as core, extended, or outlier data by these lists.
    preferences = json.loads(z.read('cldr-core/supplemental/unitPreferenceData.json'))['supplemental']['unitPreferenceData']
    region_units = {}
    for category in ('area', 'duration', 'length', 'mass', 'volume'):
        for regions in preferences[category].values():
            for region, items in regions.items():
                region_units.setdefault((category, region), set()).update(item['unit'] for item in items)
    out += ['/// Units that CLDR unit preferences list for each labeled category and region, in any usage.',
            'pub(crate) static REGION_UNITS: &[(&str, &str, &[&str])] = &[']
    out += [f'    ({rust(category)}, {rust(region)}, &[{", ".join(rust(u) for u in sorted(units))}]),'
            for (category, region), units in sorted(region_units.items())]
    out += ['];']
    dest = ROOT / 'avenger-format-number-icu'
    from usage_data import generate as generate_usage
    generate_usage(z, dest, header)
    (dest / 'src/generated.rs').write_text('\n'.join(out) + '\n')
    (dest / 'data').mkdir(exist_ok=True)
    (dest / 'data/LICENSE').write_bytes(z.read('LICENSE'))


def main():
    url = f'https://github.com/unicode-org/cldr-json/releases/download/{CLDR_VERSION}/cldr-{CLDR_VERSION}-json-full.zip'
    with TemporaryDirectory(prefix='avenger-cldr-') as directory:
        archive = Path(directory) / 'cldr.zip'
        urllib.request.urlretrieve(url, archive)
        if hashlib.sha256(archive.read_bytes()).hexdigest() != CLDR_SHA256:
            raise ValueError('CLDR archive checksum mismatch')
        with zipfile.ZipFile(archive) as z:
            generate(z)


if __name__ == '__main__':
    main()
