[package]
name = "avenger-scales"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
palette = { workspace = true }
avenger-common = { path = "../avenger-common" }

[dev-dependencies]
float-cmp = "0.10.0"
