[package]
name = "avenger-scales"
version = "0.1.0"
edition = "2021"

[features]
default = ["temporal", "arrow"]
temporal = ["dep:chrono", "dep:chrono-tz"]
arrow = ["dep:arrow"]

[dependencies]
thiserror = { workspace = true }
palette = { workspace = true }
avenger-common = { path = "../avenger-common" }
chrono = { workspace = true, optional = true }
chrono-tz = { workspace = true, optional = true }
indexmap = { workspace = true }
arrow = { workspace = true, optional = true }

[dev-dependencies]
float-cmp = "0.10.0"
