[workspace]
members = [
    "avenger",
    "avenger-vega",
    "avenger-wgpu",
    "avenger-vega-test-data",
]

resolver = "2"

[workspace.dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "^1.0"
lyon_path = "1.0.1"
lyon_extra = "1.0.1"
lyon = "1.0.1"
image = { version="0.24.8", default-features = false }
lazy_static = "1.4.0"