[workspace]
members = [
    "avenger-scenegraph",
    "avenger-vega",
    "avenger-wgpu",
    "avenger-vega-test-data",
    "avenger-python",
    "avenger-vega-renderer", 
    "avenger-scales",
    "avenger-guides",
    "avenger-common",
    "examples/wgpu-scales",
    "examples/scatter-panning",
    "examples/wgpu-winit",
]

resolver = "2"

[workspace.dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
thiserror = "2.0.3"
lyon_path = "1.0.1"
lyon_extra = "1.0.1"
lyon = "1.0.1"
image = { version = "0.25.5", default-features = false, features = ["png"] }
lazy_static = "1.4.0"
pyo3 = "0.23.2"
pythonize = "0.23.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
rayon = "1.8.1"
winit = "0.30.5"
wgpu = "23.0.1"
palette = "0.7.6"
chrono = "0.4.38"
chrono-tz = "0.10.0"
