[project]
name = "avenger"
version = "0.0.1"
description = "Add a short description here"
authors = ["Jon Mease <jonmmease@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
bump-version = { cmd = ["python", "automation/bump_version.py"] }
fmt-rs = { cmd = ["cargo", "fmt", "--all"] }
clippy = { cmd = ["cargo", "clippy", "--all-targets"] }

[tasks.publish-rs]
cmd = """
cargo publish -p avenger-common &&
cargo publish -p avenger-geometry &&
cargo publish -p avenger-text &&
cargo publish -p avenger-image &&
cargo publish -p avenger-scales &&
cargo publish -p avenger-scenegraph &&
cargo publish -p avenger-eventstream &&
cargo publish -p avenger-wgpu &&
cargo publish -p avenger-guides &&
cargo publish -p avenger-vega-scenegraph &&
cargo publish -p avenger-app &&
cargo publish -p avenger-winit-wgpu
"""

[dependencies]
python = "3.12.*"
jupyterlab = ">=4.0.11,<4.1"
maturin = ">=1.4.0,<1.5"
pip = ">=23.3.2,<23.4"
vl-convert-python = ">=1.2.2,<1.3"
altair = ">=5.2.0,<5.3"
vega_datasets = ">=0.9.0,<0.10"
vegafusion = "1.6.7.*"
vegafusion-python-embed = "1.6.7.*"
click = ">=8.1.7,<8.2"
toml = ">=0.10.2,<0.11"
nodejs = "20.*"
bokeh = ">=3.4.0,<3.5"
pixi-pycharm = ">=0.0.3,<0.1"
pillow = ">=10.3.0,<10.4"
ruff = ">=0.3.7,<0.4"
deno = ">=1.42.4,<1.43"
protobuf = ">=4.25.3,<4.26"
tree-sitter-cli = ">=0.25.3"

[pypi-dependencies]
pytest-playwright = "*"
pixelmatch = "*"
