[project]
name = "avenger"
version = "0.0.1"
description = "Add a short description here"
authors = ["Jon Mease <jonmmease@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
dev-py = { cmd = ["maturin", "develop", "-m", "avenger-python/Cargo.toml", "--release"]}
build-py = { cmd = ["maturin", "build", "-m", "avenger-python/Cargo.toml", "--sdist", "--release"]}
bump-version = { cmd = ["python", "automation/bump_version.py"] }

[tasks.publish-rs]
cmd = """
cargo publish -p avenger &&
cargo publish -p avenger-vega &&
cargo publish -p avenger-wgpu
"""

[dependencies]
python = "3.12.*"
jupyterlab = ">=4.0.11,<4.1"
maturin = ">=1.4.0,<1.5"
pip = ">=23.3.2,<23.4"
vl-convert-python = ">=1.2.2,<1.3"
altair = ">=5.2.0,<5.3"
vega_datasets = ">=0.9.0,<0.10"
vegafusion = ">=1.6.1,<1.7"
vegafusion-python-embed = ">=1.6.1,<1.7"
click = ">=8.1.7,<8.2"
toml = ">=0.10.2,<0.11"
nodejs = "20.*"
bokeh = ">=3.4.0,<3.5"
pixi-pycharm = ">=0.0.3,<0.1"
pillow = ">=10.3.0,<10.4"

[pypi-dependencies]
pytest-playwright = "*"
pixelmatch = "*"
