//! Golden-fixture comparison against d3-geo.
//!
//! Fixtures are generated by `tools/geo-fixtures/generate.mjs` (checked in;
//! regenerate with `cd tools/geo-fixtures && npm ci && npm run generate`).
//!
//! Comparison strategy:
//! - point projection/inversion: near-exact (the math is a direct port)
//! - streamed geometry: identical event order and boundaries, with each
//!   projected point compared in sequence
//! - bounds and fit: near-exact

use avenger_geo::graticule::Graticule;
use avenger_geo::projector::{BoundsSink, Projection};
use avenger_geo::raw::ProjectionKind;
use avenger_geo::stream::{RecordingSink, StreamEvent};
use avenger_geo::streamable::{Sphere, Streamable};
use geo_types::{Coord, LineString, Polygon};
use serde_json::Value;
use std::path::PathBuf;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn kind_for(name: &str) -> ProjectionKind {
    match name {
        "equirectangular" => ProjectionKind::Equirectangular,
        "mercator" => ProjectionKind::Mercator,
        "equal_earth" => ProjectionKind::EqualEarth,
        "natural_earth1" => ProjectionKind::NaturalEarth1,
        "winkel_tripel" => ProjectionKind::WinkelTripel,
        "conic_equal_area" => ProjectionKind::ConicEqualArea {
            parallels: (29.5, 45.5),
        },
        "conic_conformal" => ProjectionKind::ConicConformal {
            parallels: (35.0, 65.0),
        },
        other => panic!("unknown projection {other}"),
    }
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("number")
}

fn arr3(v: &Value) -> [f64; 3] {
    let a = v.as_array().unwrap();
    [f(&a[0]), f(&a[1]), f(&a[2])]
}

/// Test geometry, mirroring generate.mjs. Polygon rings use the d3
/// spherical winding convention.
fn stream_object(name: &str) -> Box<dyn Streamable> {
    fn line(coords: &[[f64; 2]]) -> LineString<f64> {
        LineString(coords.iter().map(|c| Coord { x: c[0], y: c[1] }).collect())
    }
    match name {
        "antimeridian_line" => Box::new(line(&[[-170.0, 10.0], [170.0, 20.0]])),
        "london_tokyo" => Box::new(line(&[[-0.1, 51.5], [139.7, 35.7]])),
        "mid_lat_square" => Box::new(Polygon::new(
            line(&[
                [10.0, 10.0],
                [10.0, 40.0],
                [40.0, 40.0],
                [40.0, 10.0],
                [10.0, 10.0],
            ]),
            vec![],
        )),
        "south_pole_ring" => Box::new(Polygon::new(
            line(&[
                [0.0, -60.0],
                [60.0, -60.0],
                [120.0, -60.0],
                [180.0, -60.0],
                [-120.0, -60.0],
                [-60.0, -60.0],
                [0.0, -60.0],
            ]),
            vec![],
        )),
        "sphere" => Box::new(Sphere),
        "graticule" => Box::new(Graticule::default().lines()),
        other => panic!("unknown stream object {other}"),
    }
}

fn parse_events(v: &Value) -> Vec<StreamEvent> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|e| {
            let e = e.as_array().unwrap();
            match e[0].as_str().unwrap() {
                "pt" => StreamEvent::Point(f(&e[1]), f(&e[2])),
                "ls" => StreamEvent::LineStart,
                "le" => StreamEvent::LineEnd,
                "ps" => StreamEvent::PolygonStart,
                "pe" => StreamEvent::PolygonEnd,
                "sp" => StreamEvent::Sphere,
                other => panic!("unknown event {other}"),
            }
        })
        .collect()
}

fn run_fixture(path: &PathBuf) {
    let text = std::fs::read_to_string(path).expect("read fixture");
    let fixture: Value = serde_json::from_str(&text).expect("parse fixture");
    let name = fixture["projection"].as_str().unwrap();
    let rotate = arr3(&fixture["rotate"]);
    let kind = kind_for(name);
    let scale = f(&fixture["scale"]);
    let translate = fixture["translate"].as_array().unwrap();
    let translate = [f(&translate[0]), f(&translate[1])];
    let precision = f(&fixture["precision"]);
    let center = fixture["center"].as_array().unwrap();
    let center = [f(&center[0]), f(&center[1])];

    // (mercator's d3-style auto world clip extent is applied by build().)
    let projection = Projection::new(kind.clone())
        .with_rotate(rotate)
        .with_center(center[0], center[1])
        .with_scale(scale)
        .with_translate(translate)
        .with_precision(precision);

    let projector = projection.build();
    let label = path.file_name().unwrap().to_string_lossy().to_string();

    // --- Points ---
    let invert_tolerance = if name == "winkel_tripel" { 1e-4 } else { 1e-6 };
    for point in fixture["points"].as_array().unwrap() {
        let lonlat = point["lonlat"].as_array().unwrap();
        let (lon, lat) = (f(&lonlat[0]), f(&lonlat[1]));
        let xy = point["xy"].as_array().unwrap();
        let (ex, ey) = (f(&xy[0]), f(&xy[1]));
        let (x, y) = projector
            .project(lon, lat)
            .unwrap_or_else(|| panic!("{label}: project ({lon}, {lat}) failed"));
        assert!(
            (x - ex).abs() < 1e-6 && (y - ey).abs() < 1e-6,
            "{label}: point ({lon}, {lat}) -> ({x}, {y}), d3 ({ex}, {ey})"
        );
        // Our inversion must round-trip to the source coordinate.
        let (lon2, lat2) = projector
            .invert(x, y)
            .unwrap_or_else(|| panic!("{label}: invert ({x}, {y}) failed"));
        let mut dlon = (lon2 - lon).abs() % 360.0;
        if dlon > 180.0 {
            dlon = 360.0 - dlon;
        }
        // At the poles longitude is degenerate.
        if lat.abs() < 90.0 - 1e-9 {
            assert!(
                dlon < invert_tolerance,
                "{label}: invert lon ({lon}, {lat}) -> ({lon2}, {lat2})"
            );
        }
        assert!(
            (lat2 - lat).abs() < invert_tolerance,
            "{label}: invert lat ({lon}, {lat}) -> ({lon2}, {lat2})"
        );
    }

    // --- Streams ---
    for (obj_name, expected_events) in fixture["streams"].as_object().unwrap() {
        let expected = parse_events(expected_events);
        let object = stream_object(obj_name);
        let mut sink = RecordingSink::default();
        projector.stream(object.as_ref(), &mut sink);
        let actual = sink.events;

        assert_eq!(
            actual.len(),
            expected.len(),
            "{label}/{obj_name}: stream event count"
        );
        for (index, (expected, actual)) in expected.iter().zip(&actual).enumerate() {
            match (expected, actual) {
                (StreamEvent::Point(ex, ey), StreamEvent::Point(ax, ay)) => assert!(
                    (ex - ax).hypot(ey - ay) < 1e-3,
                    "{label}/{obj_name} event {index}: {actual:?} != {expected:?}"
                ),
                _ => assert_eq!(actual, expected, "{label}/{obj_name} event {index}"),
            }
        }
    }

    // --- Bounds ---
    for (obj_name, expected) in fixture["bounds"].as_object().unwrap() {
        let expected = expected.as_array().unwrap();
        let e = [
            [f(&expected[0][0]), f(&expected[0][1])],
            [f(&expected[1][0]), f(&expected[1][1])],
        ];
        let object = stream_object(obj_name);
        let mut bounds = BoundsSink::default();
        projector.stream(object.as_ref(), &mut bounds);
        let b = bounds
            .result()
            .unwrap_or_else(|| panic!("{label}/{obj_name}: empty bounds"));
        for (i, j) in [(0, 0), (0, 1), (1, 0), (1, 1)] {
            let scale_ref = (e[1][0] - e[0][0]).abs().max(1.0);
            assert!(
                (b[i][j] - e[i][j]).abs() < 1e-3 * scale_ref,
                "{label}/{obj_name}: bounds {b:?} vs d3 {e:?}"
            );
        }
    }

    // --- Fit ---
    let fit = &fixture["fit"]["sphere_extent_800x600"];
    let expected_scale = f(&fit["scale"]);
    let et = fit["translate"].as_array().unwrap();
    let expected_translate = [f(&et[0]), f(&et[1])];
    let mut fit_projection = Projection::new(kind)
        .with_rotate(rotate)
        .with_center(center[0], center[1])
        .with_precision(precision);
    fit_projection
        .fit_extent([[0.0, 0.0], [800.0, 600.0]], &Sphere)
        .unwrap();
    assert!(
        (fit_projection.scale - expected_scale).abs() < 1e-3 * expected_scale.abs(),
        "{label}: fit scale {} vs d3 {expected_scale}",
        fit_projection.scale
    );
    for i in 0..2 {
        assert!(
            (fit_projection.translate[i] - expected_translate[i]).abs() < 1e-2,
            "{label}: fit translate {:?} vs d3 {expected_translate:?}",
            fit_projection.translate
        );
    }
}

#[test]
fn d3_fixture_parity() {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(fixture_dir())
        .expect("fixture dir (run tools/geo-fixtures/generate.mjs)")
        .filter_map(|e| {
            let p = e.unwrap().path();
            (p.extension().and_then(|s| s.to_str()) == Some("json")).then_some(p)
        })
        .collect();
    paths.sort();
    assert!(
        paths.len() >= 22,
        "expected 22 fixtures, found {}",
        paths.len()
    );
    for path in &paths {
        run_fixture(path);
    }
}
