//! Golden-fixture comparison against d3-geo.
//!
//! Fixtures are generated by `tools/geo-fixtures/generate.mjs` (checked in;
//! regenerate with `cd tools/geo-fixtures && npm install && npm run generate`).
//!
//! Comparison strategy (scratch/geo/phase-1-avenger-geo-engine.md §1.5):
//! - point projection/inversion: near-exact (the math is a direct port)
//! - streamed geometry: event sequences compared pointwise when shapes
//!   match; otherwise polyline point clouds compared by symmetric
//!   nearest-vertex distance (recursion order may differ) with vertex
//!   counts within ±10%
//! - bounds and fit: near-exact

use avenger_geo::graticule::Graticule;
use avenger_geo::projector::{BoundsSink, Projection};
use avenger_geo::raw::ProjectionKind;
use avenger_geo::stream::{RecordingSink, StreamEvent};
use avenger_geo::streamable::{Sphere, Streamable};
use geo_types::{Coord, LineString, Polygon};
use serde_json::Value;
use std::path::PathBuf;

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn kind_for(name: &str) -> ProjectionKind {
    match name {
        "equirectangular" => ProjectionKind::Equirectangular,
        "mercator" => ProjectionKind::Mercator,
        "equal_earth" => ProjectionKind::EqualEarth,
        "natural_earth1" => ProjectionKind::NaturalEarth1,
        "winkel_tripel" => ProjectionKind::WinkelTripel,
        "conic_equal_area" => ProjectionKind::ConicEqualArea {
            parallels: (29.5, 45.5),
        },
        "conic_conformal" => ProjectionKind::ConicConformal {
            parallels: (35.0, 65.0),
        },
        other => panic!("unknown projection {other}"),
    }
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("number")
}

fn arr3(v: &Value) -> [f64; 3] {
    let a = v.as_array().unwrap();
    [f(&a[0]), f(&a[1]), f(&a[2])]
}

/// Test geometry, mirroring generate.mjs. Polygon rings use the d3
/// spherical winding convention.
fn stream_object(name: &str) -> Box<dyn Streamable> {
    fn line(coords: &[[f64; 2]]) -> LineString<f64> {
        LineString(coords.iter().map(|c| Coord { x: c[0], y: c[1] }).collect())
    }
    match name {
        "antimeridian_line" => Box::new(line(&[[-170.0, 10.0], [170.0, 20.0]])),
        "london_tokyo" => Box::new(line(&[[-0.1, 51.5], [139.7, 35.7]])),
        "mid_lat_square" => Box::new(Polygon::new(
            line(&[
                [10.0, 10.0],
                [10.0, 40.0],
                [40.0, 40.0],
                [40.0, 10.0],
                [10.0, 10.0],
            ]),
            vec![],
        )),
        "south_pole_ring" => Box::new(Polygon::new(
            line(&[
                [0.0, -60.0],
                [60.0, -60.0],
                [120.0, -60.0],
                [180.0, -60.0],
                [-120.0, -60.0],
                [-60.0, -60.0],
                [0.0, -60.0],
            ]),
            vec![],
        )),
        "sphere" => Box::new(Sphere),
        "graticule" => Box::new(Graticule::default().lines()),
        other => panic!("unknown stream object {other}"),
    }
}

fn parse_events(v: &Value) -> Vec<StreamEvent> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|e| {
            let e = e.as_array().unwrap();
            match e[0].as_str().unwrap() {
                "pt" => StreamEvent::Point(f(&e[1]), f(&e[2])),
                "ls" => StreamEvent::LineStart,
                "le" => StreamEvent::LineEnd,
                "ps" => StreamEvent::PolygonStart,
                "pe" => StreamEvent::PolygonEnd,
                "sp" => StreamEvent::Sphere,
                other => panic!("unknown event {other}"),
            }
        })
        .collect()
}

fn event_shape(events: &[StreamEvent]) -> Vec<u8> {
    events
        .iter()
        .map(|e| match e {
            StreamEvent::Point(..) => 0,
            StreamEvent::LineStart => 1,
            StreamEvent::LineEnd => 2,
            StreamEvent::PolygonStart => 3,
            StreamEvent::PolygonEnd => 4,
            StreamEvent::Sphere => 5,
        })
        .collect()
}

fn points_of(events: &[StreamEvent]) -> Vec<[f64; 2]> {
    events
        .iter()
        .filter_map(|e| match e {
            StreamEvent::Point(x, y) => Some([*x, *y]),
            _ => None,
        })
        .collect()
}

/// Symmetric max nearest-vertex distance between two point clouds.
fn cloud_distance(a: &[[f64; 2]], b: &[[f64; 2]]) -> f64 {
    fn one_way(a: &[[f64; 2]], b: &[[f64; 2]]) -> f64 {
        let mut worst = 0.0_f64;
        for p in a {
            let mut best = f64::INFINITY;
            for q in b {
                let d = (p[0] - q[0]).hypot(p[1] - q[1]);
                if d < best {
                    best = d;
                }
            }
            if best > worst {
                worst = best;
            }
        }
        worst
    }
    one_way(a, b).max(one_way(b, a))
}

fn run_fixture(path: &PathBuf) {
    let text = std::fs::read_to_string(path).expect("read fixture");
    let fixture: Value = serde_json::from_str(&text).expect("parse fixture");
    let name = fixture["projection"].as_str().unwrap();
    let rotate = arr3(&fixture["rotate"]);
    let kind = kind_for(name);
    let scale = f(&fixture["scale"]);
    let translate = fixture["translate"].as_array().unwrap();
    let translate = [f(&translate[0]), f(&translate[1])];
    let precision = f(&fixture["precision"]);
    let center = fixture["center"].as_array().unwrap();
    let center = [f(&center[0]), f(&center[1])];

    // (mercator's d3-style auto world clip extent is applied by build().)
    let projection = Projection::new(kind.clone())
        .with_rotate(rotate)
        .with_center(center[0], center[1])
        .with_scale(scale)
        .with_translate(translate)
        .with_precision(precision);

    let projector = projection.build();
    let label = path.file_name().unwrap().to_string_lossy().to_string();

    // --- Points ---
    let invert_tolerance = if name == "winkel_tripel" { 1e-4 } else { 1e-6 };
    for point in fixture["points"].as_array().unwrap() {
        let lonlat = point["lonlat"].as_array().unwrap();
        let (lon, lat) = (f(&lonlat[0]), f(&lonlat[1]));
        let xy = point["xy"].as_array().unwrap();
        let (ex, ey) = (f(&xy[0]), f(&xy[1]));
        let (x, y) = projector
            .project(lon, lat)
            .unwrap_or_else(|| panic!("{label}: project ({lon}, {lat}) failed"));
        assert!(
            (x - ex).abs() < 1e-6 && (y - ey).abs() < 1e-6,
            "{label}: point ({lon}, {lat}) -> ({x}, {y}), d3 ({ex}, {ey})"
        );
        // Our inversion must round-trip to the source coordinate.
        let (lon2, lat2) = projector
            .invert(x, y)
            .unwrap_or_else(|| panic!("{label}: invert ({x}, {y}) failed"));
        let mut dlon = (lon2 - lon).abs() % 360.0;
        if dlon > 180.0 {
            dlon = 360.0 - dlon;
        }
        // At the poles longitude is degenerate.
        if lat.abs() < 90.0 - 1e-9 {
            assert!(
                dlon < invert_tolerance,
                "{label}: invert lon ({lon}, {lat}) -> ({lon2}, {lat2})"
            );
        }
        assert!(
            (lat2 - lat).abs() < invert_tolerance,
            "{label}: invert lat ({lon}, {lat}) -> ({lon2}, {lat2})"
        );
    }

    // --- Streams ---
    for (obj_name, expected_events) in fixture["streams"].as_object().unwrap() {
        let expected = parse_events(expected_events);
        let object = stream_object(obj_name);
        let mut sink = RecordingSink::default();
        projector.stream(object.as_ref(), &mut sink);
        let actual = sink.events;

        // Fast path: identical shape -> compare pointwise.
        if event_shape(&expected) == event_shape(&actual) {
            let mut max_d = 0.0_f64;
            for (e, a) in expected.iter().zip(actual.iter()) {
                if let (StreamEvent::Point(ex, ey), StreamEvent::Point(ax, ay)) = (e, a) {
                    let d = (ex - ax).hypot(ey - ay);
                    if d > max_d {
                        max_d = d;
                    }
                }
            }
            assert!(
                max_d < 1e-3,
                "{label}/{obj_name}: pointwise deviation {max_d}"
            );
            continue;
        }

        // Tolerant path: recursion/ring order may differ.
        let ep = points_of(&expected);
        let ap = points_of(&actual);
        assert!(
            ep.is_empty() == ap.is_empty(),
            "{label}/{obj_name}: emptiness mismatch (d3 {} pts, ours {} pts)",
            ep.len(),
            ap.len()
        );
        if ep.is_empty() {
            continue;
        }
        let ratio = ap.len() as f64 / ep.len() as f64;
        assert!(
            (0.9..=1.1).contains(&ratio),
            "{label}/{obj_name}: vertex count ratio {ratio} (d3 {}, ours {})",
            ep.len(),
            ap.len()
        );
        let d = cloud_distance(&ep, &ap);
        assert!(
            d < 0.5,
            "{label}/{obj_name}: cloud distance {d} (d3 {}, ours {} pts)",
            ep.len(),
            ap.len()
        );
    }

    // --- Bounds ---
    for (obj_name, expected) in fixture["bounds"].as_object().unwrap() {
        let expected = expected.as_array().unwrap();
        let e = [
            [f(&expected[0][0]), f(&expected[0][1])],
            [f(&expected[1][0]), f(&expected[1][1])],
        ];
        let object = stream_object(obj_name);
        let mut bounds = BoundsSink::default();
        projector.stream(object.as_ref(), &mut bounds);
        let b = bounds
            .result()
            .unwrap_or_else(|| panic!("{label}/{obj_name}: empty bounds"));
        for (i, j) in [(0, 0), (0, 1), (1, 0), (1, 1)] {
            let scale_ref = (e[1][0] - e[0][0]).abs().max(1.0);
            assert!(
                (b[i][j] - e[i][j]).abs() < 1e-3 * scale_ref,
                "{label}/{obj_name}: bounds {b:?} vs d3 {e:?}"
            );
        }
    }

    // --- Fit ---
    let fit = &fixture["fit"]["sphere_extent_800x600"];
    let expected_scale = f(&fit["scale"]);
    let et = fit["translate"].as_array().unwrap();
    let expected_translate = [f(&et[0]), f(&et[1])];
    let mut fit_projection = Projection::new(kind)
        .with_rotate(rotate)
        .with_center(center[0], center[1])
        .with_precision(precision);
    fit_projection.fit_extent([[0.0, 0.0], [800.0, 600.0]], &Sphere);
    assert!(
        (fit_projection.scale - expected_scale).abs() < 1e-3 * expected_scale.abs(),
        "{label}: fit scale {} vs d3 {expected_scale}",
        fit_projection.scale
    );
    for i in 0..2 {
        assert!(
            (fit_projection.translate[i] - expected_translate[i]).abs() < 1e-2,
            "{label}: fit translate {:?} vs d3 {expected_translate:?}",
            fit_projection.translate
        );
    }
}

#[test]
fn d3_fixture_parity() {
    let mut paths: Vec<PathBuf> = std::fs::read_dir(fixture_dir())
        .expect("fixture dir (run tools/geo-fixtures/generate.mjs)")
        .filter_map(|e| {
            let p = e.unwrap().path();
            (p.extension().and_then(|s| s.to_str()) == Some("json")).then_some(p)
        })
        .collect();
    paths.sort();
    assert!(
        paths.len() >= 21,
        "expected 21 fixtures, found {}",
        paths.len()
    );
    for path in &paths {
        run_fixture(path);
    }
}

#[test]
#[ignore]
fn debug_conformal_graticule() {
    let path = fixture_dir().join("conic_conformal_oblique.json");
    let text = std::fs::read_to_string(&path).unwrap();
    let fixture: Value = serde_json::from_str(&text).unwrap();
    let projection = Projection::new(kind_for("conic_conformal"))
        .with_rotate(arr3(&fixture["rotate"]))
        .with_scale(150.0)
        .with_translate([480.0, 250.0])
        .with_precision(f(&fixture["precision"]));
    let projector = projection.build();
    let expected = parse_events(&fixture["streams"]["graticule"]);
    let mut sink = RecordingSink::default();
    projector.stream(stream_object("graticule").as_ref(), &mut sink);

    fn lines(events: &[StreamEvent]) -> Vec<usize> {
        let mut out = Vec::new();
        let mut cur = 0usize;
        let mut in_line = false;
        for e in events {
            match e {
                StreamEvent::LineStart => {
                    in_line = true;
                    cur = 0;
                }
                StreamEvent::LineEnd => {
                    in_line = false;
                    out.push(cur);
                }
                StreamEvent::Point(..) if in_line => {
                    cur += 1;
                }
                _ => {}
            }
        }
        out
    }
    let el = lines(&expected);
    let al = lines(&sink.events);
    println!("d3 lines: {} ours: {}", el.len(), al.len());
    for i in 0..el.len().max(al.len()) {
        let e = el.get(i).copied().unwrap_or(0);
        let a = al.get(i).copied().unwrap_or(0);
        if e.abs_diff(a) > 2 {
            println!("line {i}: d3 {e} ours {a}");
        }
    }
}

#[test]
#[ignore]
fn debug_cea_oblique_fit() {
    let projection = Projection::new(kind_for("conic_equal_area"))
        .with_rotate([15.0, -30.0, 12.0])
        .with_scale(150.0)
        .with_translate([0.0, 0.0])
        .with_precision(0.5f64.sqrt());
    let projector = projection.build();
    let mut bounds = BoundsSink::default();
    projector.stream(&Sphere, &mut bounds);
    let b = bounds.result().unwrap();
    println!("our reference bounds: {:?}", b);
    // d3 fixture: fit scale/translate for 800x600
    let text =
        std::fs::read_to_string(fixture_dir().join("conic_equal_area_oblique.json")).unwrap();
    let fixture: Value = serde_json::from_str(&text).unwrap();
    let fit = &fixture["fit"]["sphere_extent_800x600"];
    let d3_scale = f(&fit["scale"]);
    let t = fit["translate"].as_array().unwrap();
    let (tx, ty) = (f(&t[0]), f(&t[1]));
    let k = d3_scale / 150.0;
    // Invert d3 fit formulas: x = (800 - k*(bx1+bx0))/2, w-limit unknown side
    println!(
        "d3 k = {k}, implied bx-sum = {}, by-sum = {}",
        (800.0 - 2.0 * tx) / k,
        (600.0 - 2.0 * ty) / k
    );
    println!(
        "our  bx-sum = {}, by-sum = {}",
        b[1][0] + b[0][0],
        b[1][1] + b[0][1]
    );
    println!("our  w = {}, h = {}", b[1][0] - b[0][0], b[1][1] - b[0][1]);
    println!(
        "k from w: {}, k from h: {}",
        800.0 / (b[1][0] - b[0][0]),
        600.0 / (b[1][1] - b[0][1])
    );
    // Sample the sphere boundary finely via projected antimeridian walk:
    let mut min_y = f64::INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    for i in 0..=3600 {
        let lat = -90.0 + (i as f64) * 0.05;
        for lon in [-179.9999, 179.9999] {
            if let Some((_, y)) = projector.project(lon, lat) {
                min_y = min_y.min(y);
                max_y = max_y.max(y);
            }
        }
    }
    println!("dense boundary y-range: {min_y}..{max_y}");
}

#[test]
#[ignore]
fn debug_mercator_oblique_sphere() {
    let text = std::fs::read_to_string(fixture_dir().join("mercator_oblique.json")).unwrap();
    let fixture: Value = serde_json::from_str(&text).unwrap();
    let projection = Projection::new(kind_for("mercator"))
        .with_rotate(arr3(&fixture["rotate"]))
        .with_scale(150.0)
        .with_translate([480.0, 250.0])
        .with_precision(f(&fixture["precision"]));
    let projector = projection.build();
    let expected = parse_events(&fixture["streams"]["sphere"]);
    let mut sink = RecordingSink::default();
    projector.stream(stream_object("sphere").as_ref(), &mut sink);
    println!("d3   ({} events):", expected.len());
    for e in &expected {
        println!("  {:?}", e);
    }
    println!("ours ({} events):", sink.events.len());
    for e in &sink.events {
        println!("  {:?}", e);
    }
}
