[package]
name = "avenger-format-datetime-chrono"
version = "0.1.0"
edition = "2021"

[features]
all-locales = ["chrono/unstable-locales"]

[dependencies]
avenger-format = { path = "../avenger-format" }
cfg-if = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true, features = ["serde"] }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
