[package]
name = "avenger-vega"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
image-request = ["reqwest"]

[dependencies]
avenger = { path = "../avenger" }
cfg-if = "1"
thiserror = { workspace = true }
serde = { workspace = true }
csscolorparser = "0.6.2"
serde_json = { version = "1.0.111" }
lyon_extra = { workspace = true }
lyon_path = { workspace = true, features = ["serialization"]}
image = { workspace = true, default-features = false, features = ["png"] }
reqwest = { version = "0.11.23", features = ["blocking"], optional = true }
pyo3 = { workspace = true, optional = true }