//! Ported from crates/typst-library/src/foundations/content/element.rs @ v0.15.1, modified for Avenger.
//!
//! avenger: upstream identifies an element by its generated vtable. Avenger's `elem!` macro
//! generates a static `NativeElementData` per element instead, which carries the names that
//! diagnostics and `Debug` output use. Capabilities are looked up through [`Capability`], which
//! the macro wires to the traits an element lists, instead of through vtable casts.

use std::fmt::{self, Debug};
use std::hash::{Hash, Hasher};

use ecow::EcoString;

use crate::typst_library::diag::SourceResult;
use crate::typst_library::engine::Engine;
use crate::typst_library::foundations::{Args, Content, Packed, StyleChain, Styles};
use crate::typst_library::math::Mathy;

/// A document element.
#[derive(Copy, Clone)]
pub struct Element(&'static NativeElementData);

impl Element {
    /// Get the element for `T`.
    pub const fn of<T: NativeElement>() -> Self {
        T::ELEM
    }

    /// Get the element from its static data. This is called by the `elem!` macro.
    pub const fn from_data(data: &'static NativeElementData) -> Self {
        Self(data)
    }

    /// The element's normal name (e.g. `enum`).
    pub fn name(self) -> &'static str {
        self.0.name
    }

    // avenger: no `title`, `docs` or `keywords`, which only documentation reads.

    /// Extract the field name for the given field ID.
    pub fn field_name(&self, id: u8) -> Option<&'static str> {
        self.0.field_names.get(usize::from(id)).copied()
    }

    /// Construct an instance of this element.
    pub fn construct(
        self,
        engine: &mut Engine,
        args: &mut Args,
    ) -> SourceResult<Content> {
        (self.0.construct)(engine, args)
    }
}

impl PartialEq for Element {
    fn eq(&self, other: &Self) -> bool {
        std::ptr::eq(self.0, other.0)
    }
}

impl Eq for Element {}

impl Hash for Element {
    fn hash<H: Hasher>(&self, state: &mut H) {
        std::ptr::hash(self.0, state);
    }
}

impl Debug for Element {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Element({})", self.name())
    }
}

/// The static data of an element, generated by the `elem!` macro.
// avenger: stands in for upstream's `ContentVtable`, without reflection or docs.
#[derive(Debug)]
pub struct NativeElementData {
    /// The element's normal name.
    pub name: &'static str,
    /// The names of the element's fields, indexed by field ID.
    pub field_names: &'static [&'static str],
    /// Constructs the element from arguments.
    pub construct: fn(&mut Engine, &mut Args) -> SourceResult<Content>,
}

/// A Typst element that is defined by a native Rust type.
// avenger: not `unsafe`, since nothing casts on the strength of `ELEM`; no `Hash`, `Construct`
// or `Set` supertraits. `PartialEq` and `repr` stand in for the vtable's field comparison and
// generic repr, and the capability methods for its capability casts. `elem!` generates them.
pub trait NativeElement: Debug + Clone + PartialEq + Send + Sync + 'static {
    /// The associated element.
    const ELEM: Element;

    /// Pack the element into type-erased content.
    fn pack(self) -> Content {
        Content::new(self)
    }

    /// The element's repr: its `Repr` impl if it has one, else `name(field: value, ..)` over the
    /// fields that are present.
    fn repr(packed: &Packed<Self>) -> EcoString;

    /// The packed element as a [`ShowSet`], if it has the capability.
    fn as_show_set(packed: &Packed<Self>) -> Option<&(dyn ShowSet + 'static)> {
        let _ = packed;
        None
    }

    /// The packed element as a [`Mathy`], if it has the capability.
    fn as_mathy(packed: &Packed<Self>) -> Option<&(dyn Mathy + 'static)> {
        let _ = packed;
        None
    }

    /// The packed element as a [`Synthesize`], if it has the capability.
    fn as_synthesize(packed: &Packed<Self>) -> Option<&(dyn Synthesize + 'static)> {
        let _ = packed;
        None
    }

    /// The packed element as a mutable [`Synthesize`], if it has the capability.
    fn as_synthesize_mut(
        packed: &mut Packed<Self>,
    ) -> Option<&mut (dyn Synthesize + 'static)> {
        let _ = packed;
        None
    }
}

/// An element's constructor function.
pub trait Construct {
    /// Construct an element from the arguments.
    ///
    /// This is passed only the arguments that remain after execution of the
    /// element's set rule.
    fn construct(engine: &mut Engine, args: &mut Args) -> SourceResult<Content>
    where
        Self: Sized;
}

// avenger: no `Set` trait, since labels have no set rules.

/// Synthesize fields on an element. This happens before execution of any show
/// rule.
pub trait Synthesize {
    /// Prepare the element for show rule application.
    fn synthesize(&mut self, engine: &mut Engine, styles: StyleChain)
    -> SourceResult<()>;
}

/// Defines built-in show set rules for an element.
///
/// This is a bit more powerful than a user-defined show-set because it can
/// access the element's fields.
pub trait ShowSet {
    /// Finalize the fully realized form of the element. Use this for effects
    /// that should work even in the face of a user-defined show rule.
    fn show_set(&self, styles: StyleChain) -> Styles;
}

// avenger: no `PlainText`; only outlines, bibliographies, footnotes and links read plain text.

/// A capability trait object that content can be cast to with [`Content::with`].
// avenger: replaces upstream's vtable-based capability casts.
pub trait Capability {
    /// Casts the content's element if it has the capability.
    fn of(content: &Content) -> Option<&Self>;
}

/// A capability trait object that content can be mutably cast to with
/// [`Content::with_mut`].
// avenger: replaces upstream's vtable-based capability casts.
pub trait CapabilityMut: Capability {
    /// Casts the content's element mutably if it has the capability, making the content
    /// unique first.
    fn of_mut(content: &mut Content) -> Option<&mut Self>;
}

impl Capability for dyn ShowSet {
    fn of(content: &Content) -> Option<&Self> {
        content.0.dyn_show_set()
    }
}

impl Capability for dyn Mathy {
    fn of(content: &Content) -> Option<&Self> {
        content.0.dyn_mathy()
    }
}

impl Capability for dyn Synthesize {
    fn of(content: &Content) -> Option<&Self> {
        content.0.dyn_synthesize()
    }
}

impl CapabilityMut for dyn Synthesize {
    fn of_mut(content: &mut Content) -> Option<&mut Self> {
        content.0.dyn_synthesize()?;
        content.make_mut().dyn_synthesize_mut()
    }
}
