// Generated by tools/icu-number-reference/generate_data.py.
// CLDR 48.2.1; archive SHA-256: 6435a529c9be2f9cbc57ba9d0e577c9c4aca90c109bb7156a4f057dfaf2a626f.
// Unicode data license: data/LICENSE.
// Precision: ICU 049e0d6a420629ac7db77256987d083a563287b5.
static PREFERENCES: &[(&str, &[Preference])] = &[
    ("area/default/001", &[
        Preference { unit: "square-kilometer", threshold: "1", precision: "" },
        Preference { unit: "hectare", threshold: "1", precision: "" },
        Preference { unit: "square-meter", threshold: "1", precision: "" },
        Preference { unit: "square-centimeter", threshold: "1", precision: "" },
    ]),
    ("area/default/GB", &[
        Preference { unit: "square-mile", threshold: "1", precision: "" },
        Preference { unit: "acre", threshold: "1", precision: "" },
        Preference { unit: "square-foot", threshold: "1", precision: "" },
        Preference { unit: "square-inch", threshold: "1", precision: "" },
    ]),
    ("area/default/US", &[
        Preference { unit: "square-mile", threshold: "1", precision: "" },
        Preference { unit: "acre", threshold: "1", precision: "" },
        Preference { unit: "square-foot", threshold: "1", precision: "" },
        Preference { unit: "square-inch", threshold: "1", precision: "" },
    ]),
    ("area/floor/001", &[
        Preference { unit: "square-meter", threshold: "1", precision: "" },
    ]),
    ("area/floor/CA", &[
        Preference { unit: "square-foot", threshold: "1", precision: "" },
    ]),
    ("area/floor/GB", &[
        Preference { unit: "square-foot", threshold: "1", precision: "" },
    ]),
    ("area/floor/MM", &[
        Preference { unit: "square-foot", threshold: "1", precision: "" },
    ]),
    ("area/floor/US", &[
        Preference { unit: "square-foot", threshold: "1", precision: "" },
    ]),
    ("area/geograph/001", &[
        Preference { unit: "square-kilometer", threshold: "1", precision: "" },
    ]),
    ("area/geograph/GB", &[
        Preference { unit: "square-mile", threshold: "1", precision: "" },
    ]),
    ("area/geograph/US", &[
        Preference { unit: "square-mile", threshold: "1", precision: "" },
    ]),
    ("area/land/001", &[
        Preference { unit: "hectare", threshold: "1", precision: "" },
    ]),
    ("area/land/GB", &[
        Preference { unit: "acre", threshold: "1", precision: "" },
    ]),
    ("area/land/US", &[
        Preference { unit: "acre", threshold: "1", precision: "" },
    ]),
    ("duration/default/001", &[
        Preference { unit: "day", threshold: "1", precision: "" },
        Preference { unit: "hour", threshold: "1", precision: "" },
        Preference { unit: "minute", threshold: "1", precision: "" },
        Preference { unit: "second", threshold: "1", precision: "" },
        Preference { unit: "millisecond", threshold: "1", precision: "" },
        Preference { unit: "microsecond", threshold: "1", precision: "" },
        Preference { unit: "nanosecond", threshold: "1", precision: "" },
    ]),
    ("duration/media/001", &[
        Preference { unit: "minute-and-second", threshold: "1", precision: "" },
        Preference { unit: "second", threshold: "1", precision: "" },
    ]),
    ("length/default/001", &[
        Preference { unit: "kilometer", threshold: "1", precision: "" },
        Preference { unit: "meter", threshold: "1", precision: "" },
        Preference { unit: "centimeter", threshold: "1", precision: "" },
    ]),
    ("length/default/GB", &[
        Preference { unit: "mile", threshold: "1", precision: "" },
        Preference { unit: "foot", threshold: "1", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/default/US", &[
        Preference { unit: "mile", threshold: "1", precision: "" },
        Preference { unit: "foot", threshold: "1", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/focal-length/001", &[
        Preference { unit: "millimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/001", &[
        Preference { unit: "centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/AT", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/BE", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/CA", &[
        Preference { unit: "foot-and-inch", threshold: "3.0", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person-height/DZ", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/EG", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/ES", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/FR", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/GB", &[
        Preference { unit: "foot-and-inch", threshold: "3.0", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person-height/HK", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/ID", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/IL", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/IN", &[
        Preference { unit: "foot-and-inch", threshold: "3.0", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person-height/IT", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/JO", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/MY", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/SA", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/SE", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/TR", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person-height/US", &[
        Preference { unit: "foot-and-inch", threshold: "3.0", precision: "" },
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person-height/VN", &[
        Preference { unit: "meter-and-centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person/001", &[
        Preference { unit: "centimeter", threshold: "1", precision: "" },
    ]),
    ("length/person/CA", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person/GB", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person/IN", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/person/US", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/rainfall/001", &[
        Preference { unit: "millimeter", threshold: "1", precision: "" },
    ]),
    ("length/rainfall/BR", &[
        Preference { unit: "centimeter", threshold: "1", precision: "" },
    ]),
    ("length/rainfall/US", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/road/001", &[
        Preference { unit: "kilometer", threshold: "0.9", precision: "" },
        Preference { unit: "meter", threshold: "300.0", precision: "precision-increment/50" },
        Preference { unit: "meter", threshold: "10", precision: "precision-increment/10" },
        Preference { unit: "meter", threshold: "1", precision: "precision-increment/1" },
    ]),
    ("length/road/GB", &[
        Preference { unit: "mile", threshold: "0.5", precision: "" },
        Preference { unit: "yard", threshold: "100.0", precision: "precision-increment/50" },
        Preference { unit: "yard", threshold: "10", precision: "precision-increment/10" },
        Preference { unit: "yard", threshold: "1", precision: "precision-increment/1" },
    ]),
    ("length/road/SE", &[
        Preference { unit: "mile-scandinavian", threshold: "1", precision: "" },
        Preference { unit: "kilometer", threshold: "1", precision: "" },
        Preference { unit: "meter", threshold: "300.0", precision: "precision-increment/50" },
        Preference { unit: "meter", threshold: "10", precision: "precision-increment/10" },
        Preference { unit: "meter", threshold: "1", precision: "precision-increment/1" },
    ]),
    ("length/road/US", &[
        Preference { unit: "mile", threshold: "0.5", precision: "" },
        Preference { unit: "foot", threshold: "100.0", precision: "precision-increment/50" },
        Preference { unit: "foot", threshold: "10", precision: "precision-increment/10" },
        Preference { unit: "foot", threshold: "1", precision: "precision-increment/1" },
    ]),
    ("length/snowfall/001", &[
        Preference { unit: "centimeter", threshold: "1", precision: "" },
    ]),
    ("length/snowfall/US", &[
        Preference { unit: "inch", threshold: "1", precision: "" },
    ]),
    ("length/vehicle/001", &[
        Preference { unit: "meter", threshold: "1", precision: "" },
    ]),
    ("length/vehicle/GB", &[
        Preference { unit: "foot-and-inch", threshold: "1", precision: "" },
    ]),
    ("length/vehicle/US", &[
        Preference { unit: "foot-and-inch", threshold: "1", precision: "" },
    ]),
    ("length/visiblty/001", &[
        Preference { unit: "kilometer", threshold: "0.1", precision: "" },
        Preference { unit: "meter", threshold: "1", precision: "" },
    ]),
    ("length/visiblty/DE", &[
        Preference { unit: "meter", threshold: "1", precision: "" },
    ]),
    ("length/visiblty/GB", &[
        Preference { unit: "mile", threshold: "1", precision: "" },
        Preference { unit: "foot", threshold: "1", precision: "" },
    ]),
    ("length/visiblty/NL", &[
        Preference { unit: "meter", threshold: "1", precision: "" },
    ]),
    ("length/visiblty/US", &[
        Preference { unit: "mile", threshold: "1", precision: "" },
        Preference { unit: "foot", threshold: "1", precision: "" },
    ]),
    ("mass/default/001", &[
        Preference { unit: "tonne", threshold: "1", precision: "" },
        Preference { unit: "kilogram", threshold: "1", precision: "" },
        Preference { unit: "gram", threshold: "1", precision: "" },
        Preference { unit: "milligram", threshold: "1", precision: "" },
        Preference { unit: "microgram", threshold: "1", precision: "" },
    ]),
    ("mass/default/GB", &[
        Preference { unit: "ton", threshold: "1", precision: "" },
        Preference { unit: "pound", threshold: "1", precision: "" },
        Preference { unit: "ounce", threshold: "1", precision: "" },
    ]),
    ("mass/default/US", &[
        Preference { unit: "ton", threshold: "1", precision: "" },
        Preference { unit: "pound", threshold: "1", precision: "" },
        Preference { unit: "ounce", threshold: "1", precision: "" },
    ]),
    ("mass/person/001", &[
        Preference { unit: "kilogram", threshold: "1", precision: "" },
        Preference { unit: "gram", threshold: "1", precision: "" },
    ]),
    ("mass/person/GB", &[
        Preference { unit: "stone-and-pound", threshold: "1", precision: "" },
        Preference { unit: "pound-and-ounce", threshold: "1", precision: "" },
    ]),
    ("mass/person/HK", &[
        Preference { unit: "pound-and-ounce", threshold: "1", precision: "" },
    ]),
    ("mass/person/US", &[
        Preference { unit: "pound", threshold: "1", precision: "" },
        Preference { unit: "pound-and-ounce", threshold: "1", precision: "" },
    ]),
    ("volume/default/001", &[
        Preference { unit: "cubic-meter", threshold: "1", precision: "" },
        Preference { unit: "cubic-centimeter", threshold: "1", precision: "" },
    ]),
    ("volume/default/GB", &[
        Preference { unit: "cubic-foot", threshold: "1", precision: "" },
        Preference { unit: "cubic-inch", threshold: "1", precision: "" },
    ]),
    ("volume/default/US", &[
        Preference { unit: "cubic-foot", threshold: "1", precision: "" },
        Preference { unit: "cubic-inch", threshold: "1", precision: "" },
    ]),
    ("volume/fluid/001", &[
        Preference { unit: "liter", threshold: "1", precision: "" },
        Preference { unit: "milliliter", threshold: "1", precision: "" },
    ]),
    ("volume/fluid/GB", &[
        Preference { unit: "gallon-imperial", threshold: "1", precision: "" },
        Preference { unit: "fluid-ounce-imperial", threshold: "1", precision: "" },
    ]),
    ("volume/fluid/US", &[
        Preference { unit: "gallon", threshold: "1", precision: "" },
        Preference { unit: "quart", threshold: "1", precision: "" },
        Preference { unit: "pint", threshold: "1", precision: "" },
        Preference { unit: "cup", threshold: "1", precision: "" },
        Preference { unit: "fluid-ounce", threshold: "1", precision: "" },
        Preference { unit: "tablespoon", threshold: "1", precision: "" },
        Preference { unit: "teaspoon", threshold: "1", precision: "" },
    ]),
    ("volume/oil/001", &[
        Preference { unit: "barrel", threshold: "1", precision: "" },
    ]),
    ("volume/vehicle/001", &[
        Preference { unit: "liter", threshold: "1", precision: "" },
    ]),
    ("volume/vehicle/US", &[
        Preference { unit: "gallon", threshold: "1", precision: "" },
    ]),
];
static BASE_UNITS: &[(&str, &str, &[&str])] = &[
    ("acre", "square-meter", &["ussystem", "uksystem"]),
    ("astronomical-unit", "meter", &["astronomical", "si_acceptable"]),
    ("barrel", "cubic-meter", &["ussystem"]),
    ("bu-jp", "square-meter", &["jpsystem"]),
    ("bushel", "cubic-meter", &["ussystem"]),
    ("carat", "kilogram", &["metric_adjacent", "ussystem", "uksystem"]),
    ("chain", "meter", &["ussystem", "uksystem"]),
    ("cho", "square-meter", &["jpsystem"]),
    ("cup", "cubic-meter", &["ussystem"]),
    ("cup-imperial", "cubic-meter", &["uksystem"]),
    ("cup-jp", "cubic-meter", &["jpsystem"]),
    ("cup-metric", "cubic-meter", &["metric_adjacent"]),
    ("dalton", "kilogram", &["si_acceptable", "metric", "prefixable"]),
    ("day", "second", &["si_acceptable", "metric_adjacent", "prefixable", "ussystem", "uksystem", "astronomical"]),
    ("day-person", "second", &["person_age"]),
    ("dessert-spoon", "cubic-meter", &["ussystem"]),
    ("dessert-spoon-imperial", "cubic-meter", &["uksystem"]),
    ("dram", "cubic-meter", &["ussystem"]),
    ("drop", "cubic-meter", &["ussystem"]),
    ("dunam", "square-meter", &["metric_adjacent"]),
    ("earth-mass", "kilogram", &["astronomical"]),
    ("earth-radius", "meter", &["astronomical"]),
    ("fathom", "meter", &["ussystem", "uksystem"]),
    ("fluid-ounce", "cubic-meter", &["ussystem"]),
    ("fluid-ounce-imperial", "cubic-meter", &["uksystem"]),
    ("fluid-ounce-metric", "cubic-meter", &["metric_adjacent"]),
    ("foot", "meter", &["ussystem", "uksystem"]),
    ("fortnight", "second", &["ussystem", "uksystem"]),
    ("fun", "kilogram", &["jpsystem"]),
    ("furlong", "meter", &["ussystem", "uksystem"]),
    ("gallon", "cubic-meter", &["ussystem"]),
    ("gallon-imperial", "cubic-meter", &["uksystem"]),
    ("grain", "kilogram", &["ussystem", "uksystem"]),
    ("gram", "kilogram", &["si", "metric", "prefixable"]),
    ("hectare", "square-meter", &["si_acceptable", "metric"]),
    ("hour", "second", &["si_acceptable", "metric_adjacent", "prefixable", "ussystem", "uksystem", "astronomical"]),
    ("inch", "meter", &["ussystem", "uksystem"]),
    ("jigger", "cubic-meter", &["ussystem"]),
    ("jo-jp", "meter", &["jpsystem"]),
    ("ken", "meter", &["jpsystem"]),
    ("kilogram", "kilogram", &["si", "metric"]),
    ("koku", "cubic-meter", &["jpsystem"]),
    ("kosaji", "cubic-meter", &["jpsystem"]),
    ("light-year", "meter", &["astronomical"]),
    ("liter", "cubic-meter", &["si_acceptable", "metric", "prefixable"]),
    ("meter", "meter", &["si", "metric", "prefixable"]),
    ("mile", "meter", &["ussystem", "uksystem"]),
    ("mile-scandinavian", "meter", &["metric_adjacent"]),
    ("minute", "second", &["si_acceptable", "metric_adjacent", "prefixable", "ussystem", "uksystem", "astronomical"]),
    ("nautical-mile", "meter", &["ussystem", "uksystem", "si_acceptable"]),
    ("osaji", "cubic-meter", &["jpsystem"]),
    ("ounce", "kilogram", &["ussystem", "uksystem"]),
    ("ounce-troy", "kilogram", &["ussystem", "uksystem"]),
    ("parsec", "meter", &["astronomical", "prefixable"]),
    ("pinch", "cubic-meter", &["ussystem"]),
    ("pint", "cubic-meter", &["ussystem"]),
    ("pint-imperial", "cubic-meter", &["uksystem"]),
    ("pint-metric", "cubic-meter", &["metric_adjacent"]),
    ("point", "meter", &["metric_adjacent", "ussystem", "uksystem"]),
    ("pound", "kilogram", &["ussystem", "uksystem"]),
    ("quart", "cubic-meter", &["ussystem"]),
    ("quart-imperial", "cubic-meter", &["uksystem"]),
    ("ri-jp", "meter", &["jpsystem"]),
    ("rin", "meter", &["jpsystem"]),
    ("rod", "meter", &["ussystem", "uksystem"]),
    ("sai", "cubic-meter", &["jpsystem"]),
    ("se-jp", "square-meter", &["jpsystem"]),
    ("second", "second", &["si", "metric", "prefixable", "ussystem", "uksystem", "astronomical"]),
    ("shaku", "cubic-meter", &["jpsystem"]),
    ("shaku-cloth", "meter", &["jpsystem"]),
    ("shaku-length", "meter", &["jpsystem"]),
    ("slug", "kilogram", &["ussystem", "uksystem"]),
    ("solar-mass", "kilogram", &["astronomical"]),
    ("solar-radius", "meter", &["astronomical"]),
    ("stone", "kilogram", &["uksystem"]),
    ("sun", "meter", &["jpsystem"]),
    ("tablespoon", "cubic-meter", &["ussystem"]),
    ("teaspoon", "cubic-meter", &["ussystem"]),
    ("to-jp", "cubic-meter", &["jpsystem"]),
    ("ton", "kilogram", &["ussystem", "uksystem"]),
    ("tonne", "kilogram", &["si_acceptable", "metric", "prefixable"]),
    ("week", "second", &["metric_adjacent", "ussystem", "uksystem", "astronomical"]),
    ("week-person", "second", &["person_age"]),
    ("yard", "meter", &["ussystem", "uksystem"]),
];
static CATEGORIES: &[(&str, &str)] = &[
    ("ampere", "electric-current"),
    ("ampere-per-meter", "magnetic-field-strength"),
    ("ampere-per-square-meter", "current-density"),
    ("bit", "digital"),
    ("candela", "luminous-intensity"),
    ("candela-per-square-meter", "illuminance"),
    ("candela-square-meter-per-square-meter", "luminous-flux"),
    ("cubic-meter", "volume"),
    ("cubic-meter-per-kilogram", "specific-volume"),
    ("cubic-meter-per-meter", "consumption"),
    ("cubic-second-square-ampere-per-kilogram-square-meter", "electric-conductance"),
    ("em", "typewidth"),
    ("item", "substance-amount"),
    ("item-per-cubic-meter", "concentration"),
    ("item-per-kilogram", "concentration-mass"),
    ("item-per-second", "catalytic-activity"),
    ("kelvin", "temperature"),
    ("kilogram", "mass"),
    ("kilogram-meter-per-square-second", "force"),
    ("kilogram-per-cubic-meter", "mass-density"),
    ("kilogram-per-kilogram", "mass-fraction"),
    ("kilogram-per-meter-square-second", "pressure"),
    ("kilogram-per-square-meter-square-second", "pressure-per-length"),
    ("kilogram-per-square-second-ampere", "magnetic-induction"),
    ("kilogram-square-meter-per-cubic-second", "power"),
    ("kilogram-square-meter-per-cubic-second-ampere", "voltage"),
    ("kilogram-square-meter-per-cubic-second-square-ampere", "electric-resistance"),
    ("kilogram-square-meter-per-square-second", "energy"),
    ("kilogram-square-meter-per-square-second-ampere", "magnetic-flux"),
    ("kilogram-square-meter-per-square-second-square-ampere", "electric-inductance"),
    ("meter", "length"),
    ("meter-per-second", "speed"),
    ("meter-per-square-second", "acceleration"),
    ("night", "night-duration"),
    ("part", "portion"),
    ("per-second", "radioactivity"),
    ("pixel", "graphics"),
    ("pixel-per-meter", "resolution"),
    ("pow4-second-square-ampere-per-kilogram-square-meter", "electric-capacitance"),
    ("revolution", "angle"),
    ("revolution-per-meter", "wave-number"),
    ("revolution-per-second", "frequency"),
    ("second", "duration"),
    ("second-ampere", "electric-charge"),
    ("square-meter", "area"),
    ("square-meter-per-square-second", "ionizing-radiation"),
    ("square-revolution", "solid-angle"),
    ("year", "year-duration"),
];
