[package]
name = "avenger-app"
version = "0.1.0"
edition = "2021"

[dependencies]
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-eventstream = { path = "../avenger-eventstream" }
avenger-geometry = { path = "../avenger-geometry" }
winit = { workspace = true }