[package]
name = "avenger-pdf"
version = "0.0.8"
edition = "2021"
description = "PDF renderer for Avenger scene graphs"
license = "BSD-3-Clause"

[dependencies]
thiserror = { workspace = true }
svg2pdf = { workspace = true }

[dependencies.avenger-scenegraph]
path = "../avenger-scenegraph"
version = "0.0.8"

[dependencies.avenger-svg]
path = "../avenger-svg"
version = "0.0.8"

[dependencies.avenger-text]
path = "../avenger-text"
default-features = false

[dev-dependencies.avenger-color]
path = "../avenger-color"

[dev-dependencies.avenger-common]
path = "../avenger-common"
