[package]
name = "wgpu-winit"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
avenger-vega-scenegraph = { path = "../../avenger-vega-scenegraph", default-features = false }
avenger-wgpu = { path = "../../avenger-wgpu", default-features = false }
avenger-image = { path = "../../avenger-image", default-features = false }
avenger-scenegraph = { path = "../../avenger-scenegraph" }
avenger-common = { path = "../../avenger-common" }

cfg-if = "1"
winit = "0.30.5"
env_logger = "0.10"
log = "0.4"
wgpu = "25.0.2"
pollster = "0.3"
serde_json = { version = "1.0.111" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
console_log = "1.0"
wgpu = { version = "25.0.2", features = ["webgl", "webgpu"]}
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = { version = "0.4.42" }
web-sys = { version = "0.3.67", features = [
    "Document",
    "Window",
    "Element",
]}