[package]
name = "avenger-annotation"
version = "0.1.0"
edition = "2021"

[dependencies]
avenger-color = { path = "../avenger-color" }
avenger-common = { path = "../avenger-common" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-typst-label = { path = "../avenger-typst-label" }
lyon_path = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
avenger-typst-label = { path = "../avenger-typst-label", features = ["bundled-fonts"] }
