[project]
name = "avenger"
version = "0.0.2"

[build-system]
requires = [ "maturin>=1.1.0,<2",]
build-backend = "maturin"

[tool.maturin]
module-name = "avenger._avenger"

[project.entry-points."altair.vegalite.v5.renderer"]
avenger-png = "avenger.altair_utils:avenger_png_renderer"
