use std::collections::HashMap;
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let book_src = manifest_dir.join("../book/src");
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let doc_out = out_dir.join("book_docs.rs");
    let render_out = out_dir.join("render_snippets.rs");

    let mut docs = Vec::new();
    let mut render_blocks = Vec::new();
    collect_markdown(&book_src, &book_src, &mut docs, &mut render_blocks)?;

    docs.sort_by(|a, b| a.0.cmp(&b.0));

    let mut seen = HashMap::new();
    let mut doc_file = File::create(doc_out)?;

    writeln!(
        doc_file,
        "// Auto-generated documentation modules for mdBook snippets."
    )?;
    writeln!(
        doc_file,
        "// This file is generated by build.rs in avenger-chart-mdbook."
    )?;

    for (rel_path, full_path) in &docs {
        let identifier = make_identifier(rel_path, &mut seen);
        let path_literal = full_path.to_string_lossy().replace('\\', "\\\\");
        writeln!(
            doc_file,
            "#[doc = include_str!(\"{}\")]\npub mod {} {{}}\n",
            path_literal, identifier
        )?;
    }

    generate_render_snippets(&render_out, &render_blocks)?;

    Ok(())
}

#[derive(Debug)]
struct RenderBlock {
    rel_path: String,
    fence_index: usize,
    slug: String,
    fn_ident: String,
    code: String,
    image_count: usize, // 1 for single Plot, N for tuple of N EvaluatedPlots
}

fn collect_markdown(
    root: &Path,
    dir: &Path,
    docs: &mut Vec<(String, PathBuf)>,
    render_blocks: &mut Vec<RenderBlock>,
) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_markdown(root, &path, docs, render_blocks)?;
        } else if path.extension().map(|ext| ext == "md").unwrap_or(false) {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            docs.push((rel.clone(), path.clone()));

            let mut file = File::open(&path)?;
            let mut content = String::new();
            file.read_to_string(&mut content)?;

            let mut fence_counter = 0usize;
            for code in extract_render_blocks(&content) {
                let slug = make_slug(&rel, fence_counter);
                let fn_ident = make_fn_ident(&slug);
                let (processed_code, image_count) = process_render_code(&code);
                render_blocks.push(RenderBlock {
                    rel_path: rel.clone(),
                    fence_index: fence_counter,
                    slug,
                    fn_ident,
                    code: processed_code,
                    image_count,
                });
                fence_counter += 1;
            }
        }
    }
    Ok(())
}

fn make_identifier(rel_path: &str, seen: &mut HashMap<String, usize>) -> String {
    let mut base = String::with_capacity(rel_path.len() + 4);
    base.push_str("doc_");
    for ch in rel_path.chars() {
        if ch.is_ascii_alphanumeric() {
            base.push(ch.to_ascii_lowercase());
        } else {
            base.push('_');
        }
    }
    if base
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(false)
    {
        base.insert(0, '_');
    }
    let counter = seen.entry(base.clone()).or_insert(0);
    let mut ident = base.clone();
    if *counter > 0 {
        ident.push('_');
        ident.push_str(&counter.to_string());
    }
    *counter += 1;
    ident
}

fn make_slug(rel_path: &str, index: usize) -> String {
    let mut slug = rel_path
        .trim_end_matches(".md")
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() {
                ch.to_ascii_lowercase()
            } else {
                '_'
            }
        })
        .collect::<String>();
    while slug.contains("__") {
        slug = slug.replace("__", "_");
    }
    slug = slug.trim_matches('_').to_string();
    if slug.is_empty() {
        slug.push_str("snippet");
    }
    format!("{}_render{:02}", slug, index)
}

fn make_fn_ident(slug: &str) -> String {
    let mut ident = String::from("render_");
    ident.push_str(
        &slug
            .chars()
            .map(|ch| if ch.is_ascii_alphanumeric() { ch } else { '_' })
            .collect::<String>(),
    );
    ident
}

fn extract_render_blocks(content: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut lines = content.lines();
    let mut current = Vec::new();
    let mut capture = false;

    while let Some(line) = lines.next() {
        if let Some(info) = line.strip_prefix("```") {
            if capture {
                blocks.push(current.join("\n"));
                current.clear();
                capture = false;
            } else if is_render_fence(info.trim()) {
                capture = true;
            }
            continue;
        }

        if capture {
            current.push(line.to_string());
        }
    }

    blocks
}

fn is_render_fence(info: &str) -> bool {
    let normalized = info.replace(',', " ");
    let mut saw_rust = false;
    let mut saw_render = false;
    let mut saw_ignore = false;
    for token in normalized.split_whitespace() {
        match token {
            "rust" | "" => saw_rust = true,
            "render" => saw_render = true,
            "ignore" => saw_ignore = true,
            _ => {}
        }
    }
    saw_rust && saw_render && !saw_ignore
}

/// Process render code block and detect if it returns a single EvaluatedPlot
/// or a tuple of EvaluatedPlots.
/// Returns (processed_code, image_count) where image_count is 1 for single
/// EvaluatedPlot or N for tuple of N EvaluatedPlots.
fn process_render_code(code: &str) -> (String, usize) {
    let body = code.trim_end();

    // Find the last non-empty, non-comment line
    let last_line = body
        .lines()
        .rev()
        .map(|l| l.trim())
        .find(|l| !l.is_empty() && !l.starts_with("//"))
        .unwrap_or("");

    // Check if it's a tuple by looking for pattern like (result1, result2, ...)
    // Simple heuristic: starts with '(' and contains at least one comma
    if last_line.starts_with('(') && last_line.contains(',') {
        // Count commas to estimate tuple size (rough heuristic)
        let comma_count = last_line.matches(',').count();
        let image_count = comma_count + 1;

        let mut processed = body.to_string();
        if !processed.ends_with('\n') {
            processed.push('\n');
        }
        return (processed, image_count);
    }

    // Single EvaluatedPlot - ensure it ends with the variable name
    let mut processed = body.to_string();
    if !processed.ends_with('\n') {
        processed.push('\n');
    }
    (processed, 1)
}

fn generate_render_snippets(out_path: &Path, snippets: &[RenderBlock]) -> io::Result<()> {
    let mut file = File::create(out_path)?;

    writeln!(file, "use std::path::Path;")?;
    writeln!(file, "use std::boxed::Box;")?;
    writeln!(file, "use tokio::runtime::Runtime;")?;
    writeln!(
        file,
        "use avenger_chart::doc::render::render_evaluated_plot_to_png;"
    )?;
    writeln!(
        file,
        "#[allow(unused_imports)] use avenger_chart::prelude::*;"
    )?;
    writeln!(file, "#[allow(unused_imports)] use datafusion::prelude::*;")?;
    writeln!(
        file,
        "#[allow(unused_imports)] use avenger_chart::doc::datasets;"
    )?;
    writeln!(file, "#[allow(unused_imports)] use indexmap::IndexMap;")?;
    writeln!(
        file,
        "#[allow(unused_imports)] use datafusion::common::ScalarValue;"
    )?;
    writeln!(file, "use std::error::Error;\n")?;

    writeln!(
        file,
        "pub struct RenderEntry {{\n    pub slug: &'static str,\n    pub markdown_path: &'static str,\n    pub fence_index: usize,\n    pub image_count: usize,\n    pub render: fn(&Path) -> Result<(), Box<dyn Error + Send + Sync + 'static>>,\n}}\n"
    )?;

    for snippet in snippets {
        writeln!(file, "#[allow(unused_imports)]")?;
        writeln!(
            file,
            "fn {}(output: &Path) -> Result<(), Box<dyn Error + Send + Sync + 'static>> {{",
            snippet.fn_ident
        )?;
        writeln!(file, "    let runtime = Runtime::new()?;")?;
        writeln!(file, "    runtime.block_on(async {{")?;

        if snippet.image_count == 1 {
            // Single EvaluatedPlot
            writeln!(file, "        let evaluated = {{")?;
            for line in snippet.code.lines() {
                let normalized = normalize_hidden_line(line);
                writeln!(file, "            {}", normalized)?;
            }
            writeln!(file, "        }};")?;
            writeln!(
                file,
                "        let output_path = output.with_extension(\"png\");"
            )?;
            writeln!(
                file,
                "        render_evaluated_plot_to_png(&evaluated, output_path).await"
            )?;
        } else {
            // Tuple of EvaluatedPlots
            writeln!(file, "        let results = {{")?;
            for line in snippet.code.lines() {
                let normalized = normalize_hidden_line(line);
                writeln!(file, "            {}", normalized)?;
            }
            writeln!(file, "        }};")?;
            writeln!(file)?;
            writeln!(file, "        // Unpack tuple and render each result")?;
            writeln!(file, "        let tuple = (")?;
            for i in 0..snippet.image_count {
                if i < snippet.image_count - 1 {
                    writeln!(file, "            &results.{},", i)?;
                } else {
                    writeln!(file, "            &results.{}", i)?;
                }
            }
            writeln!(file, "        );")?;
            writeln!(file)?;
            writeln!(
                file,
                "        let base_path = output.to_str().expect(\"valid path\");"
            )?;
            for i in 0..snippet.image_count {
                writeln!(
                    file,
                    "        let img_path_{} = format!(\"{{}}_{:02}.png\", base_path);",
                    i, i
                )?;
                writeln!(
                    file,
                    "        render_evaluated_plot_to_png(tuple.{}, &img_path_{}).await?;",
                    i, i
                )?;
            }
            writeln!(file, "        Ok(())")?;
        }

        writeln!(file, "    }})")?;
        writeln!(file, "}}\n")?;
    }

    writeln!(file, "pub static RENDER_ENTRIES: &[RenderEntry] = &[")?;
    for snippet in snippets {
        writeln!(
            file,
            "    RenderEntry {{ slug: \"{}\", markdown_path: \"{}\", fence_index: {}, image_count: {}, render: {} }},",
            snippet.slug,
            snippet.rel_path,
            snippet.fence_index,
            snippet.image_count,
            snippet.fn_ident
        )?;
    }
    writeln!(file, "];\n")?;

    Ok(())
}

fn normalize_hidden_line(line: &str) -> String {
    let trimmed = line.trim_start();
    if let Some(stripped) = trimmed.strip_prefix("# ") {
        format!("{}", stripped)
    } else if trimmed == "#" {
        String::new()
    } else {
        line.to_string()
    }
}
