[package]
name = "avenger-chart-mdbook"
version = "0.0.0"
edition = "2021"
publish = false
build = "build.rs"

[[bin]]
name = "mdbook-avenger"
path = "src/bin/mdbook-avenger.rs"

[[bin]]
name = "mdbook-avenger-render"
path = "src/bin/mdbook-avenger-render.rs"

[dependencies]
avenger-chart = { path = ".." }
avenger-wgpu = { path = "../../avenger-wgpu" }
avenger-sample-data = { path = "../../avenger-sample-data" }
datafusion = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = { workspace = true }
indexmap = { workspace = true }
palette = { workspace = true }
bincode = "1.3"
pathdiff = "0.2"
anyhow = "1.0"
mdbook = "0.4"
