#!/usr/bin/env python3
"""Generate or check avenger-typst-label's vendored Typst sources.

A generated file is the pinned upstream file minus the whole items listed in
manifest.toml, with the crate paths `crate::`, `typst_utils::` and
`typst_timing::` rewritten to Avenger's module paths, and with doc examples
marked `ignore`, under a header that names its source and says how it was
modified. Nothing else may differ.
Files marked `shim` are Avenger-owned; the check only requires them to exist.
The check also rejects files in a generated directory that the manifest
doesn't list.

  sync.py generate --typst <sources> --crate avenger-typst-label
  sync.py check    --typst <sources> --crate avenger-typst-label

`<sources>` is a directory of extracted crates.io packages
(`typst-syntax-<version>/src/...`, as check.sh prepares) or a Typst git
checkout, read at the manifest's `rev`.
"""
import argparse, difflib, os, re, subprocess, sys, tomllib
sys.path.insert(0, os.path.dirname(__file__))
from rust_items import parse, walk

REWRITES = {
    # upstream crate -> Avenger module path rewrites
    "typst-syntax": [(r"(?<![\w])crate::", "crate::typst_syntax::"),
                     (r"(?<![\w:])typst_utils::", "crate::typst_utils::"),
                     (r"(?<![\w:])typst_timing::", "crate::typst_timing::")],
    "typst-utils": [(r"(?<![\w])crate::", "crate::typst_utils::")],
}

def ignore_doc_examples(text):
    """Mark doc examples without an info string `ignore`. They are written against
    upstream's crates (`use typst_utils::...`), and rustdoc tests every example in
    a crate, private items included."""
    out, inside = [], False
    for line in text.split("\n"):
        fence = re.match(r"^(\s*//[/!] ?)```(.*)$", line)
        if fence:
            if not inside and not fence.group(2).strip():
                line = f"{fence.group(1)}```ignore"
            inside = not inside
        out.append(line)
    return "\n".join(out)

# Files that may sit in a generated directory without a manifest entry.
ALLOWED_EXTRA = {"rustfmt.toml"}

def upstream_text(typst, rev, path, version=None):
    """Read `path` (for example crates/typst-syntax/src/ast.rs) from extracted
    crates.io packages, or from a git checkout at `rev`."""
    crate, rel = path.removeprefix("crates/").split("/", 1)
    packaged = os.path.join(typst, f"{crate}-{version}", rel)
    if version and os.path.exists(packaged):
        return open(packaged).read()
    return subprocess.run(["git", "-C", typst, "show", f"{rev}:{path}"],
                          check=True, capture_output=True, text=True).stdout

def find(items, sel):
    multi = sel.endswith("*")
    key = sel[:-1] if multi else sel
    hits = [it for p, it in walk(items) if p + it.selector == key]
    if not hits or (len(hits) > 1 and not multi):
        raise SystemExit(f"selector {sel!r} matched {len(hits)} items")
    return hits

def drop_ranges(lines, ranges):
    keep = [True] * len(lines)
    for lo, hi in ranges:
        for k in range(lo, hi + 1):
            keep[k] = False
    out = [line for k, line in enumerate(lines) if keep[k]]
    # Collapse blank runs and blank lines just inside braces, as rustfmt would.
    res = []
    for line in out:
        if not line.strip() and res and (not res[-1].strip() or res[-1].rstrip().endswith("{")):
            continue
        if line.strip() in ("}", "};") and res and not res[-1].strip():
            res.pop()
        res.append(line)
    while res and not res[0].strip():
        res.pop(0)
    return res

def render(entry, typst, rev, version=None):
    text = upstream_text(typst, rev, entry["src"], version)
    lines, items = parse(text)
    ranges = []
    if "remove" in entry:
        removed = set()
        for sel in entry["remove"]:
            for it in find(items, sel):
                removed.add(id(it))
        # An impl or mod whose members are all removed goes as a whole.
        for _, it in walk(items):
            if it.children and all(id(c) in removed or c.kind == "use" for c in it.children) \
                    and any(id(c) in removed for c in it.children):
                removed.add(id(it))
        ranges += [(it.start, it.end) for _, it in walk(items) if id(it) in removed]
    elif "keep" in entry:
        kept = set()
        for sel in entry["keep"]:
            for it in find(items, sel):
                kept.add(id(it))
        ranges += [(it.start, it.end) for it in items if id(it) not in kept]
    out = "\n".join(drop_ranges(lines, ranges))
    for pat, rep in REWRITES[entry["crate"]]:
        out = re.sub(pat, rep, out)
    return header(entry, version or rev) + ignore_doc_examples(out)

def header(entry, version):
    """The notice that a generated file is a modified copy of its upstream file."""
    return (f"// Generated by tools/typst-sync from {entry['src']} @ v{version}, modified for\n"
            "// Avenger: items listed in its manifest are removed and crate paths are rewritten.\n")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["generate", "check"])
    ap.add_argument("--typst", required=True, help="crates.io sources or a Typst checkout")
    ap.add_argument("--crate", required=True, help="avenger-typst-label directory")
    ap.add_argument("--manifest", default=os.path.join(os.path.dirname(__file__), "manifest.toml"))
    a = ap.parse_args()
    man = tomllib.load(open(a.manifest, "rb"))
    rev = man["upstream"]["rev"]
    version = man["upstream"].get("version")
    bad = 0
    generated_dirs = set()
    listed = set()
    for entry in man["file"]:
        dst = os.path.join(a.crate, entry["dst"])
        listed.add(os.path.normpath(entry["dst"]))
        if entry.get("mode") == "shim":
            if not os.path.exists(dst):
                print(f"missing shim {entry['dst']}"); bad += 1
            continue
        generated_dirs.add(os.path.dirname(entry["dst"]))
        want = render(entry, a.typst, rev, version)
        if a.cmd == "generate":
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            open(dst, "w").write(want)
            print(f"wrote {entry['dst']} ({want.count(chr(10))} lines)")
        else:
            have = open(dst).read() if os.path.exists(dst) else ""
            if have != want:
                bad += 1
                sys.stdout.writelines(difflib.unified_diff(
                    want.splitlines(True), have.splitlines(True),
                    f"expected/{entry['dst']}", f"actual/{entry['dst']}"))
    for rel_dir in sorted(generated_dirs):
        for name in sorted(os.listdir(os.path.join(a.crate, rel_dir))):
            rel = os.path.normpath(os.path.join(rel_dir, name))
            if rel not in listed and name not in ALLOWED_EXTRA:
                print(f"{rel} is in a generated directory but not in the manifest"); bad += 1
    if a.cmd == "check":
        print("typst-sync: OK" if not bad else f"typst-sync: {bad} problem(s)")
    sys.exit(1 if bad else 0)

if __name__ == "__main__":
    main()
