[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[env]
CC_wasm32_unknown_unknown = { value = "scripts/wasm-cc", relative = true }
AR_wasm32_unknown_unknown = { value = "scripts/wasm-ar", relative = true }
