//! EPSG:4326 climate grid on Equal Earth — the xarray world's most common
//! raster, displayed without resampling.
//!
//! A lat/lon-uniform temperature grid (5° cells, long-form parquet fixture)
//! is assembled into a CRS-tagged raster struct and rendered with
//! `UniformRaster2D<Geo>`: because the rows are uniform in latitude, the
//! mark always takes the warped path, and the grid bends with the Equal
//! Earth graticule. Land outlines draw on top for orientation. Pan with the
//! left mouse button, scroll to zoom, double-click to reset.
//!
//! The fixture at `avenger-chart/tests/data/geo/climate_grid_4326.parquet`
//! is synthetic (zonal mean + longitudinal wave) and regenerated by this
//! example whenever the file is missing.
//!
//! Run with:
//! ```bash
//! cargo run --release -p avenger-chart-app --example climate_grid_equal_earth --features winit-wgpu
//! ```

use std::{path::PathBuf, sync::Arc};

use avenger_chart::prelude::*;
use avenger_chart_app::{
    ChartAppOptions, ChartResizeBinding, WinitWgpuAvengerApp, WinitWgpuAvengerAppOptions,
    chart_avenger_app,
};
use avenger_chart_geo::{
    Geo, GeoPanZoom, GeoShape, GeoUniformRaster2DChannels, GraticuleStyle, SphereStyle,
    UniformRaster2D, crs, register_geojson,
};
use datafusion::arrow::{
    array::{
        ArrayRef, Float64Array, Float64Builder, ListArray, ListBuilder, StringArray, StringBuilder,
        StructArray, UInt32Array,
    },
    buffer::OffsetBuffer,
    datatypes::{DataType, Field},
    record_batch::RecordBatch,
};
use datafusion::prelude::SessionContext;
use palette::rgb::Srgba;
use winit::window::WindowAttributes;

// 5° cells over lon [-180, 180] x lat [-85, 85].
const LON_START: f64 = -180.0;
const LON_STOP: f64 = 180.0;
const LON_BINS: u32 = 72;
const LAT_START: f64 = -85.0;
const LAT_STOP: f64 = 85.0;
const LAT_BINS: u32 = 34;

fn main() {
    init_diagnostics();
    let tokio_runtime = tokio::runtime::Builder::new_current_thread()
        .build()
        .expect("build tokio runtime");
    let avenger_app = tokio_runtime.block_on(build_app());
    let options = WinitWgpuAvengerAppOptions::new(2.0).window_attributes(
        WindowAttributes::default()
            .with_title("avenger-chart Geo: EPSG:4326 climate grid")
            .with_resizable(false),
    );
    let (mut app, event_loop) =
        WinitWgpuAvengerApp::new_and_event_loop_with_options(avenger_app, options, tokio_runtime);
    event_loop.run_app(&mut app).expect("run app");
}

async fn build_app() -> avenger_app::app::AvengerApp<avenger_chart_app::ChartAppState> {
    let ctx = Arc::new(SessionContext::new());
    let fixture = fixture_path();
    if !fixture.exists() {
        generate_fixture(&fixture);
        println!("generated climate grid fixture at {}", fixture.display());
    }
    let values = load_grid_values(&ctx, &fixture).await;
    let df = ctx
        .read_batch(raster_batch(&values))
        .expect("read raster batch");

    let land_path = format!(
        "{}/../avenger-chart/tests/data/geo/ne_110m_land.geojson",
        env!("CARGO_MANIFEST_DIR")
    );
    let land = register_geojson(&ctx, "land", land_path)
        .await
        .expect("register land");

    let geo = Geo::equal_earth()
        .viewport_id("world")
        .sphere(SphereStyle::default())
        .graticule(GraticuleStyle::default());
    let plot = Chart::with_coord(geo.clone())
        .canvas_size(900.0, 560.0)
        // Kept short: text raster entries wider than the 2048px text atlas
        // hard-error in the interactive renderer (see text.rs allocation).
        .title("Synthetic annual-mean temperature")
        .data(df)
        .mark(
            UniformRaster2D::<Geo>::new()
                .raster_with(col("raster"), |r| {
                    r.x(dim("lon")).y(dim("lat")).fill(|fill| {
                        fill.scale_with::<Linear>(|scale| {
                            scale
                                .clamp(true)
                                .domain((-30.0, 32.0))
                                .range_colors(vec![
                                    Srgba::new(0.19, 0.21, 0.58, 1.0), // deep blue
                                    Srgba::new(0.94, 0.95, 0.92, 1.0), // near-white
                                    Srgba::new(0.75, 0.10, 0.13, 1.0), // deep red
                                ])
                                .nice(false)
                                .zero(false)
                        })
                        .legend(|legend| legend.title("°C"))
                    })
                })
                .smooth(true)
                .opacity(0.92),
        )
        .mark(
            GeoShape::new()
                .data(land)
                .geometry(&geo, col("geometry"))
                .fill("#00000000")
                .stroke("#374151")
                .stroke_width(0.5),
        )
        .tool(GeoPanZoom::new().viewport_id("world"));

    let compiled = plot.compile(&ctx).await.expect("compile plot");
    chart_avenger_app(
        compiled,
        ctx,
        ChartAppOptions {
            resize_binding: ChartResizeBinding::none(),
            resize_throttle_ms: None,
            exact_on_resize_settle: true,
            log_metrics: false,
        },
    )
    .await
    .expect("build chart app")
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../avenger-chart/tests/data/geo/climate_grid_4326.parquet")
}

/// Synthetic zonal temperature with a longitudinal wave, cell centers in
/// lat-major row order (the same order `values.data` uses).
fn synthetic_temperature(lon: f64, lat: f64) -> f64 {
    let lat_rad = lat.to_radians();
    let lon_rad = lon.to_radians();
    -25.0 + 55.0 * lat_rad.cos().powf(1.5) + 5.0 * (3.0 * lon_rad).sin() * lat_rad.cos()
}

fn generate_fixture(path: &PathBuf) {
    use datafusion::parquet::arrow::ArrowWriter;

    let lon_step = (LON_STOP - LON_START) / f64::from(LON_BINS);
    let lat_step = (LAT_STOP - LAT_START) / f64::from(LAT_BINS);
    let mut lons = Vec::new();
    let mut lats = Vec::new();
    let mut temps = Vec::new();
    for iy in 0..LAT_BINS {
        for ix in 0..LON_BINS {
            let lon = LON_START + (f64::from(ix) + 0.5) * lon_step;
            let lat = LAT_START + (f64::from(iy) + 0.5) * lat_step;
            lons.push(lon);
            lats.push(lat);
            temps.push(synthetic_temperature(lon, lat));
        }
    }
    let batch = RecordBatch::try_from_iter(vec![
        ("lon", Arc::new(Float64Array::from(lons)) as ArrayRef),
        ("lat", Arc::new(Float64Array::from(lats)) as ArrayRef),
        ("t_celsius", Arc::new(Float64Array::from(temps)) as ArrayRef),
    ])
    .expect("fixture batch");
    let file = std::fs::File::create(path).expect("create fixture file");
    let mut writer = ArrowWriter::try_new(file, batch.schema(), None).expect("parquet writer");
    writer.write(&batch).expect("write fixture");
    writer.close().expect("close fixture");
}

/// Read the long-form grid back in fixture row order (lat-major).
async fn load_grid_values(ctx: &SessionContext, path: &PathBuf) -> Vec<f64> {
    let batches = ctx
        .read_parquet(
            path.to_str().expect("fixture path utf-8"),
            Default::default(),
        )
        .await
        .expect("read climate fixture")
        .collect()
        .await
        .expect("collect climate fixture");
    let mut values = Vec::with_capacity((LON_BINS * LAT_BINS) as usize);
    for batch in &batches {
        let column = batch
            .column_by_name("t_celsius")
            .expect("t_celsius column")
            .as_any()
            .downcast_ref::<Float64Array>()
            .expect("float column");
        values.extend(column.values().iter().copied());
    }
    assert_eq!(
        values.len(),
        (LON_BINS * LAT_BINS) as usize,
        "fixture must hold one row per grid cell"
    );
    values
}

/// Wrap the dense cell values into the CRS-tagged raster struct the mark
/// consumes: `geometry.crs = "epsg:4326"`, lat/lon uniform dimensions,
/// `values.dims = [lat, lon]` (row-major, lat-major like the fixture).
fn raster_batch(cell_values: &[f64]) -> RecordBatch {
    let mut values = ListBuilder::new(Float64Builder::new());
    for value in cell_values {
        values.values().append_value(*value);
    }
    values.append(true);
    let values = Arc::new(values.finish()) as ArrayRef;

    let one_row_list = |array: ArrayRef| -> ArrayRef {
        let offsets = OffsetBuffer::from_lengths([array.len()]);
        Arc::new(
            ListArray::try_new(
                Arc::new(Field::new_list_field(array.data_type().clone(), true)),
                offsets,
                array,
                None,
            )
            .expect("list array"),
        ) as ArrayRef
    };
    let coords = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("kind", DataType::Utf8, false)),
            Arc::new(StringArray::from(vec!["uniform", "uniform"])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("sampling", DataType::Utf8, true)),
            Arc::new(StringArray::from(vec![None::<&str>, None])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("start", DataType::Float64, true)),
            Arc::new(Float64Array::from(vec![Some(LON_START), Some(LAT_START)])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("stop", DataType::Float64, true)),
            Arc::new(Float64Array::from(vec![Some(LON_STOP), Some(LAT_STOP)])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("count", DataType::UInt32, true)),
            Arc::new(UInt32Array::from(vec![Some(LON_BINS), Some(LAT_BINS)])) as ArrayRef,
        ),
    ])) as ArrayRef;
    let dimensions = one_row_list(Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("name", DataType::Utf8, false)),
            Arc::new(StringArray::from(vec!["lon", "lat"])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("coords", coords.data_type().clone(), false)),
            coords,
        ),
    ])) as ArrayRef);
    let geometry = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("kind", DataType::Utf8, false)),
            Arc::new(StringArray::from(vec!["grid"])) as ArrayRef,
        ),
        (
            Arc::new(Field::new("crs", DataType::Utf8, true)),
            Arc::new(StringArray::from(vec![Some(crs::EPSG_4326)])) as ArrayRef,
        ),
        (
            Arc::new(Field::new(
                "dimensions",
                dimensions.data_type().clone(),
                false,
            )),
            dimensions,
        ),
    ])) as ArrayRef;
    let dims = {
        let mut builder = ListBuilder::new(StringBuilder::new());
        builder.values().append_value("lat");
        builder.values().append_value("lon");
        builder.append(true);
        Arc::new(builder.finish()) as ArrayRef
    };
    let values_struct = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("dims", dims.data_type().clone(), false)),
            dims,
        ),
        (
            Arc::new(Field::new("data", values.data_type().clone(), false)),
            values,
        ),
    ])) as ArrayRef;
    let raster = Arc::new(StructArray::from(vec![
        (
            Arc::new(Field::new("geometry", geometry.data_type().clone(), false)),
            geometry,
        ),
        (
            Arc::new(Field::new(
                "values",
                values_struct.data_type().clone(),
                false,
            )),
            values_struct,
        ),
    ])) as ArrayRef;
    RecordBatch::try_from_iter(vec![("raster", raster)]).expect("raster batch")
}

fn init_diagnostics() {
    if std::env::var_os("RUST_LOG").is_some() {
        let _ = tracing_subscriber::fmt()
            .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
            .with_span_events(tracing_subscriber::fmt::format::FmtSpan::CLOSE)
            .try_init();
    } else {
        let _ = env_logger::try_init();
    }
}
