[package]
name = "avenger-chart-core"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-guides = { path = "../avenger-guides" }
avenger-common = { path = "../avenger-common" }
avenger-scales = { path = "../avenger-scales" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-text = { path = "../avenger-text" }
async-trait = { workspace = true }
base64 = { workspace = true }
cssparser = "0.35"
datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-proto = "48.0.1"
datafusion-proto-common = "48.0.1"
futures = { workspace = true }
indexmap = { workspace = true }
palette = { workspace = true }
paste = { workspace = true }
precomputed-hash = "0.1"
prost = "0.13"
serde = { workspace = true }
serde_with = "3.0"
selectors = "0.31"
strsim = "0.11"
taffy = "0.8.3"
thiserror = { workspace = true }
tracing = { workspace = true }
typetag = "0.2"

[dev-dependencies]
bincode = "1.3"
serde_json = { workspace = true }
