use std::{any::Any, collections::HashMap, sync::Arc};

use avenger_scales::scales::{ConfiguredScale, ScaleImpl};
use avenger_scenegraph::marks::mark::SceneMark;
use datafusion::{
    arrow::datatypes::DataType,
    arrow::record_batch::RecordBatch,
    dataframe::DataFrame,
    logical_expr::{Expr, lit},
    prelude::SessionContext,
    scalar::ScalarValue,
};
use datafusion_common::ScalarValue as DatafusionScalarValue;
use indexmap::IndexMap;

use crate::{
    AdjustmentTransformRequirements, AvengerChartError, ChannelDescriptor, ChannelValue,
    CompiledDataContext, CompiledMarkState, CompiledSubplotPayload, CoordinateSystemTransformCore,
    EvaluationContext, EventDatumFieldSpec, LegendRendererSelection, MarkRenderContext,
    MarkRuntimeContext, PositionedSubplotMarkCore, RadiusExpression, ResolvedDomain, ScaleRange,
    ScaleTypePreference, Theme, default_scale_type_for_data_type, is_continuous_scale,
};

pub struct RenderedMarkData {
    pub marks: Vec<SceneMark>,
    pub source_row_indices: Option<Vec<Vec<usize>>>,
    pub event_datum_rows: Option<Vec<RecordBatch>>,
}

impl RenderedMarkData {
    pub fn new(marks: Vec<SceneMark>) -> Self {
        Self {
            marks,
            source_row_indices: None,
            event_datum_rows: None,
        }
    }

    pub fn with_source_row_indices(
        marks: Vec<SceneMark>,
        source_row_indices: Vec<Vec<usize>>,
    ) -> Self {
        Self {
            marks,
            source_row_indices: Some(source_row_indices),
            event_datum_rows: None,
        }
    }

    pub fn with_source_row_indices_and_event_datum_rows(
        marks: Vec<SceneMark>,
        source_row_indices: Vec<Vec<usize>>,
        event_datum_rows: Vec<RecordBatch>,
    ) -> Self {
        Self {
            marks,
            source_row_indices: Some(source_row_indices),
            event_datum_rows: Some(event_datum_rows),
        }
    }
}

/// Mark-owned scale-domain contribution.
///
/// Most marks infer scale domains directly from their render channels. Some
/// marks, such as raster-like marks, have coordinate geometry nested inside a
/// single render datum and need to contribute scale domains from expressions
/// that are not themselves render-prepared channels.
#[derive(Clone)]
pub struct MarkScaleDomainSource {
    pub channel: String,
    pub channel_value: ChannelValue,
    pub dataframe: DataFrame,
    pub exprs: Vec<Expr>,
}

/// Core-safe compiled mark metadata and planning behavior.
///
/// This trait contains the compiled-mark surface needed for channel planning,
/// scale/domain inference, legend selection, and mark default lookup. The
/// top-level chart crate layers its render hook on top while rendering still
/// needs chart runtime state.
pub trait CompiledMarkCore: Any + Send + Sync {
    /// Get the mark's state (compiled version with CompiledDataContext).
    fn state(&self) -> &CompiledMarkState;

    /// Get mutable reference to the mark's state.
    fn state_mut(&mut self) -> &mut CompiledMarkState;

    /// Get the data context for this mark.
    fn data_context(&self) -> &CompiledDataContext;

    /// Get the mark type name (e.g., "rect", "line", "symbol").
    fn mark_type(&self) -> &str;

    /// Downcast support.
    fn as_any(&self) -> &dyn Any {
        panic!("as_any not implemented for this mark type")
    }

    /// Return a coordinate-positioned subplot view when this mark is one.
    fn as_positioned_subplot(&self) -> Option<&dyn PositionedSubplotMarkCore> {
        None
    }

    /// Return a coordinate-slot overlay view when this mark owns one.
    fn as_coordinate_slot_overlay(&self) -> Option<&dyn CoordinateSlotOverlayMarkCore> {
        None
    }

    /// Child plots owned by this mark for schema and interaction traversal.
    fn child_plot_payloads(&self) -> Vec<&CompiledSubplotPayload> {
        if let Some(subplot) = self.as_positioned_subplot() {
            vec![subplot.payload()]
        } else if let Some(overlay) = self.as_coordinate_slot_overlay() {
            vec![overlay.payload()]
        } else {
            Vec::new()
        }
    }

    /// Declare channels this mark supports.
    fn supported_channels(&self) -> Vec<ChannelDescriptor>;

    /// Whether this mark type supports the order encoding channel.
    fn supports_order(&self) -> bool {
        false
    }

    /// Whether this mark needs the full DataFrame as RecordBatch.
    fn wants_full_data_batch(&self) -> bool {
        false
    }

    /// Whether detail fields should split continuous geometry into separate
    /// rendered scene marks.
    fn details_partition_continuous_geometry(&self) -> bool {
        false
    }

    /// Event datum fields generated by this mark in addition to source-data fields.
    fn event_datum_field_specs(&self) -> Vec<EventDatumFieldSpec> {
        Vec::new()
    }

    /// Returns the default value for a channel if not explicitly mapped.
    fn default_channel_value(
        &self,
        channel: &str,
        context: &MarkRenderContext<'_>,
    ) -> Option<ScalarValue> {
        default_channel_value_for_eval(self, channel, context.eval())
    }

    /// Mark-specific default values.
    fn mark_specific_default(&self, _channel: &str) -> Option<ScalarValue> {
        None
    }

    /// Returns expressions for computing radius/padding along a dimension.
    fn radius_expression(
        &self,
        _dimension: &str,
        _resolve_channel: &dyn Fn(&str) -> Expr,
    ) -> Option<RadiusExpression> {
        None
    }

    /// Return mark-owned scale-domain sources that are not ordinary render
    /// channels.
    fn scale_domain_sources(
        &self,
        _domain_dataframe: Option<&DataFrame>,
        _ctx: &SessionContext,
    ) -> Result<Vec<MarkScaleDomainSource>, AvengerChartError> {
        Ok(Vec::new())
    }

    /// Get the name of the channel used for sorting this mark's data.
    fn sorting_channel(&self) -> Option<&str> {
        if self.supports_order() {
            Some("order")
        } else {
            None
        }
    }

    /// Get the preferred legend renderer for a channel.
    fn preferred_legend_renderer(
        &self,
        _channel: &str,
        _scale: &ConfiguredScale,
    ) -> Option<LegendRendererSelection> {
        None
    }

    /// Get the preferred scale type for a channel based on data type.
    fn preferred_scale_type(
        &self,
        _channel: &str,
        data_type: &DataType,
    ) -> Option<ScaleTypePreference> {
        default_scale_type_for_data_type(data_type)
    }

    /// Get default scale options for a channel and scale type.
    fn default_scale_options(
        &self,
        channel: &str,
        scale_impl: &dyn ScaleImpl,
        _data_type: &DataType,
    ) -> HashMap<String, Expr> {
        let mut options = HashMap::new();

        if matches!(channel, "fill" | "stroke" | "color") && is_continuous_scale(scale_impl) {
            options.insert("nice".to_string(), lit(true));
        }

        options
    }

    /// Get default range for a channel after domain has been determined.
    fn default_channel_range(
        &self,
        _channel: &str,
        _scale_impl: &dyn ScaleImpl,
        _domain: &ResolvedDomain,
        _data_type: &DataType,
        _theme: &Theme,
        _params: &IndexMap<String, DatafusionScalarValue>,
    ) -> Option<ScaleRange> {
        None
    }
}

/// A compiled mark that renders a child plot over a generated coordinate slot.
pub trait CoordinateSlotOverlayMarkCore: Send + Sync {
    fn payload(&self) -> &CompiledSubplotPayload;
    fn slot_id(&self) -> &str;
    fn width_px(&self) -> f32;
    fn x_offset_px(&self) -> f32;
    fn clip_child_frame(&self) -> bool;
    fn show_child_chrome(&self) -> bool;

    /// Child-local x fallback domain supplied when the child omits an x scale.
    fn child_x_fallback_domain(&self) -> Option<(f32, f32)> {
        Some((0.0, 1.0))
    }

    /// Child coordinate channel that should use the selected parent slot scale.
    fn parent_scale_override_channel(&self) -> Option<&str> {
        Some("y")
    }

    /// Label used in user-facing overlay validation messages.
    fn overlay_label(&self) -> &'static str {
        "CoordinateSlotOverlay"
    }

    /// Prefix for generated scenegraph groups wrapping overlay child plots.
    fn scene_group_prefix(&self) -> &'static str {
        "coordinate_slot_overlay"
    }
}

#[typetag::serde(tag = "type")]
#[async_trait::async_trait]
pub trait CompiledMark: CompiledMarkCore {
    /// Render the mark from prepared data batches.
    async fn render_from_data(
        &self,
        data: Option<&RecordBatch>,
        scalars: &RecordBatch,
        context: &dyn MarkRuntimeContext,
        coord: &dyn CoordinateSystemTransformCore,
    ) -> Result<Vec<SceneMark>, AvengerChartError>;

    async fn render_mark_data(
        &self,
        data: Option<&RecordBatch>,
        scalars: &RecordBatch,
        context: &dyn MarkRuntimeContext,
        coord: &dyn CoordinateSystemTransformCore,
    ) -> Result<RenderedMarkData, AvengerChartError> {
        self.render_from_data(data, scalars, context, coord)
            .await
            .map(RenderedMarkData::new)
    }

    fn has_render_stage_derived(&self) -> bool {
        false
    }

    fn derived_adjustment_requirements(&self) -> AdjustmentTransformRequirements {
        AdjustmentTransformRequirements::default()
    }

    async fn render_base_mark_data(
        &self,
        data: Option<&RecordBatch>,
        scalars: &RecordBatch,
        context: &dyn MarkRuntimeContext,
        coord: &dyn CoordinateSystemTransformCore,
    ) -> Result<RenderedMarkData, AvengerChartError> {
        self.render_mark_data(data, scalars, context, coord).await
    }

    async fn render_derived_mark_data(
        &self,
        _data: Option<&RecordBatch>,
        _scalars: &RecordBatch,
        _context: &dyn MarkRuntimeContext,
        _coord: &dyn CoordinateSystemTransformCore,
    ) -> Result<RenderedMarkData, AvengerChartError> {
        Ok(RenderedMarkData::new(Vec::new()))
    }
}

/// Resolve a compiled mark's default channel value from the base evaluation context.
pub fn default_channel_value_for_eval<M: CompiledMarkCore + ?Sized>(
    mark: &M,
    channel: &str,
    eval_ctx: &EvaluationContext,
) -> Option<ScalarValue> {
    if let Some(default) = eval_ctx.mark_default(mark.mark_type(), channel) {
        return Some(default);
    }

    mark.mark_specific_default(channel)
}

/// Extract a display title for a channel from compiled mark encodings.
///
/// Coordinate guides use this to derive default axis titles without depending
/// on the top-level render-capable compiled mark trait.
pub fn extract_channel_title_from_marks<M: CompiledMarkCore + ?Sized>(
    marks: &[Arc<M>],
    channel: &str,
    session_context: &SessionContext,
) -> Option<String> {
    for mark in marks {
        if let Some(channel_value) = mark.data_context().channels().get(channel)
            && let Some(col_name) = channel_value.as_column_name(session_context)
            && let Some(expr) = channel_value.expr(session_context)
            && !expr.column_refs().is_empty()
        {
            return Some(col_name);
        }
    }

    let secondary_channel = match channel {
        "x" => "x2",
        "y" => "y2",
        _ => return None,
    };

    for mark in marks {
        if let Some(channel_value) = mark.data_context().channels().get(secondary_channel)
            && let Some(col_name) = channel_value.as_column_name(session_context)
            && let Some(expr) = channel_value.expr(session_context)
            && !expr.column_refs().is_empty()
        {
            return Some(col_name);
        }
    }

    None
}
