[package]
name = "avenger-chart-parallel"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-color = { path = "../avenger-color" }
avenger-chart-core = { path = "../avenger-chart-core" }
avenger-chart-marks = { path = "../avenger-chart-marks" }
avenger-common = { path = "../avenger-common" }
avenger-scales = { path = "../avenger-scales" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-proto = "48.0.1"
indexmap = { workspace = true }
serde = { workspace = true }
serde_with = "3.0"
typetag = "0.2"

[dev-dependencies]
serde_json = { workspace = true }
