[package]
name = "avenger-chart-cartesian"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-color = { path = "../avenger-color" }
avenger-chart-core = { path = "../avenger-chart-core" }
avenger-chart-marks = { path = "../avenger-chart-marks" }
avenger-common = { path = "../avenger-common" }
avenger-format-number = { path = "../avenger-format-number" }
avenger-geometry = { path = "../avenger-geometry" }
avenger-guides = { path = "../avenger-guides" }
avenger-image = { path = "../avenger-image", default-features = false }
avenger-scales = { path = "../avenger-scales" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-text = { path = "../avenger-text" }
async-trait = { workspace = true }
datafusion = { workspace = true }
datafusion-proto = "48.0.1"
indexmap = { workspace = true }
lyon_extra = { workspace = true }
lyon_path = { workspace = true }
serde = { workspace = true }
serde_with = "3.0"
typetag = "0.2"
