[package]
name = "avenger-chart-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-chart-cartesian = { path = "../avenger-chart-cartesian" }
avenger-chart-core = { path = "../avenger-chart-core" }
avenger-chart-marks = { path = "../avenger-chart-marks" }
datafusion = { workspace = true }
