[package]
name = "avenger-typst"
version = "0.1.0"
edition = "2021"

[features]
default = []
raster = ["dep:image", "dep:tiny-skia"]
serde = ["dep:serde"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
fontdb = { workspace = true }
image = { workspace = true, optional = true }
rustybuzz = { workspace = true }
ttf-parser = { workspace = true }
tiny-skia = { workspace = true, optional = true }
unicode-bidi = "0.3.18"
unicode-math-class = "0.1"
unicode-script = "0.5.7"
unicode-segmentation = "1.12.0"
