[package]
name = "avenger-typst"
version = "0.1.0"
edition = "2021"

[features]
default = []
owned = [
    "dep:fontdb",
    "dep:rustybuzz",
    "dep:ttf-parser",
    "dep:unicode-bidi",
    "dep:unicode-math-class",
    "dep:unicode-script",
    "dep:unicode-segmentation",
]
vendor-typst = [
    "owned",
    "dep:comemo",
    "dep:typst-layout",
    "dep:typst-library",
    "dep:typst-syntax",
    "dep:typst-utils",
]
raster = ["dep:tiny-skia"]
serde = ["dep:serde"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, optional = true }
comemo = { version = "0.5.1", optional = true }
fontdb = { workspace = true, optional = true }
rustybuzz = { workspace = true, optional = true }
ttf-parser = { workspace = true, optional = true }
tiny-skia = { workspace = true, optional = true }
unicode-bidi = { version = "0.3.18", optional = true }
unicode-math-class = { version = "0.1", optional = true }
unicode-script = { version = "0.5.7", optional = true }
unicode-segmentation = { version = "1.12.0", optional = true }
typst-layout = { package = "avenger-typst-layout", path = "../vendor/typst-avenger/crates/typst-layout", optional = true }
typst-library = { package = "avenger-typst-library", path = "../vendor/typst-avenger/crates/typst-library", optional = true }
typst-syntax = { package = "avenger-typst-syntax", path = "../vendor/typst-avenger/crates/typst-syntax", optional = true }
typst-utils = { package = "avenger-typst-utils", path = "../vendor/typst-avenger/crates/typst-utils", optional = true }
