[package]
name = "avenger-format-datetime-icu"
version = "0.1.0"
edition = "2021"

[dependencies]
avenger-format = { path = "../avenger-format" }
chrono = { workspace = true }
chrono-tz = { workspace = true, features = ["serde"] }
serde = { workspace = true }
icu_calendar = { version = "~2.3.0", default-features = false, features = ["compiled_data"] }
icu_datetime = { version = "~2.3.0", default-features = false, features = ["compiled_data"] }
icu_locale_core = { version = "~2.3.0", default-features = false }
icu_provider = { version = "~2.3.0", default-features = false, features = ["sync"] }
icu_time = { version = "~2.3.0", default-features = false, features = ["compiled_data"] }
writeable = "0.6"

[dev-dependencies]
serde_json = { workspace = true }
