[package]
name = "winit-annotation-editor"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]

[dependencies]
avenger-annotation = { path = "../../avenger-annotation" }
avenger-app = { path = "../../avenger-app" }
avenger-common = { path = "../../avenger-common" }
avenger-color = { path = "../../avenger-color" }
avenger-eventstream = { path = "../../avenger-eventstream" }
avenger-format = { path = "../../avenger-format" }
avenger-format-number-d3 = { path = "../../avenger-format-number-d3" }
avenger-geometry = { path = "../../avenger-geometry" }
avenger-scales = { path = "../../avenger-scales" }
avenger-scenegraph = { path = "../../avenger-scenegraph" }
avenger-typst-label = { path = "../../avenger-typst-label", features = ["bundled-fonts"] }
avenger-wgpu = { path = "../../avenger-wgpu", default-features = false }
avenger-winit-wgpu = { path = "../../avenger-winit-wgpu" }
arrow = { workspace = true }
async-trait = { workspace = true }
unicode-segmentation = "1.12.0"
winit = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
avenger-wgpu = { path = "../../avenger-wgpu", default-features = false, features = ["rayon"] }
tokio = { workspace = true, features = ["rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
log = { workspace = true }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Navigator"] }

[dev-dependencies]
pollster = "0.4"
