[package]
name = "avenger-winit-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
avenger-common = { path = "../avenger-common" }
avenger-app = { path = "../avenger-app" }
avenger-eventstream = { path = "../avenger-eventstream" }
avenger-resource = { path = "../avenger-resource" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-wgpu = { path = "../avenger-wgpu", default-features = false }
winit = { workspace = true }
wgpu = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
cfg-if = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }


[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true, features = ["macros"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Clipboard",
    "ClipboardEvent",
    "CompositionEvent",
    "CssStyleDeclaration",
    "DataTransfer",
    "Document",
    "DomRect",
    "Element",
    "Event",
    "EventTarget",
    "FocusEvent",
    "HtmlCanvasElement",
    "HtmlElement",
    "HtmlInputElement",
    "InputEvent",
    "KeyboardEvent",
    "PointerEvent",
    "Navigator",
    "Node",
    "Window",
] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
avenger-wgpu = { path = "../avenger-wgpu", default-features = false, features = ["rayon"] }
notify = "8.0.0"
tokio = { workspace = true, features = ["rt"] }
arboard = { workspace = true }
