[package]
name = "avenger-chart-scales"
version = "0.1.0"
edition = "2024"

[dependencies]
avenger-chart-core = { path = "../avenger-chart-core" }
avenger-common = { path = "../avenger-common" }
avenger-format-number = { path = "../avenger-format-number" }
avenger-scales = { path = "../avenger-scales" }
arrow = { workspace = true }
datafusion = { workspace = true }
datafusion-common = { workspace = true }
datafusion-proto = { version = "54.0.0", default-features = false }
futures = { workspace = true }
indexmap = { workspace = true }
palette = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = "3.0"
tracing = { workspace = true }
typetag = "0.2"

[dev-dependencies]
async-trait = { workspace = true }
avenger-scenegraph = { path = "../avenger-scenegraph" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
