name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rs:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "check-linux"
      - name: Check cargo fmt compliance
        run: cargo fmt --all -- --check
      - name: Check no rustc warnings
        run: cargo check --tests
      - name: Check for clippy warnings
        run: cargo clippy
      - name: Build
        run: cargo build --verbose
#  # Tests currently fail with `MakeWgpuAdapterError`
#      - name: Run tests
#        run: cargo test --verbose

# # Cleanup fails with: [__NSCFString bytes]: unrecognized selector sent to instance 0x600002fc62c0
#  test-rs-macos:
#    runs-on: macos-latest
#    env:
#      RUSTFLAGS: "-D warnings"
#    steps:
#      - name: Install Protoc
#        uses: arduino/setup-protoc@v2
#        with:
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#      - uses: actions/checkout@v3
#      - name: Install latest stable toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#      - uses: Swatinem/rust-cache@v2
#        with:
#          prefix-key: "test-macos"
#      - name: version
#        run: rustc --version
#      - name: test
#        run:  cd avenger-wgpu/ && cargo test -- --nocapture
#      - name: Update images
#        uses: actions/upload-artifact@v4
#        with:
#          name: images-macos
#          path: avenger-wgpu/tests/output