[package]
name = "avenger-egui"
version = "0.1.0"
edition = "2024"

[features]
default = []
eframe = ["dep:eframe"]

[dependencies]
avenger-app = { path = "../avenger-app" }
avenger-common = { path = "../avenger-common" }
avenger-eventstream = { path = "../avenger-eventstream" }
avenger-resource = { path = "../avenger-resource" }
avenger-scenegraph = { path = "../avenger-scenegraph" }
avenger-wgpu = { path = "../avenger-wgpu" }

egui = { workspace = true }
egui-wgpu = { workspace = true }
eframe = { version = "0.33.3", optional = true, default-features = false, features = [
    "default_fonts",
    "wgpu",
] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
avenger-color = { path = "../avenger-color" }
avenger-geometry = { path = "../avenger-geometry" }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

[[example]]
name = "low_level_app"
required-features = ["eframe"]
